### ISSUE TITLE
Subscriptions Renewal Problem

### ISSUE THREAD

**Issue by apalazzin** [wpovernight/woocommerce-pdf-invoices-packing-slips#10]
**PLUGIN**
I'm using ```Woocommerce Subscriptions vers. 2.0.1``` and ```WooCommerce PDF Invoices & Packing Slips vers. 1.5.23```

**INVOICE SETTING**
PDF invoice attached when Customer Completed Order email

**TEST**
* If one user purchase first subscription --> it's ok
* With renewal --> there is a PROBLEM (none invoice and none mail are generated)

**ERROR LOG**
```
PHP Warning: Missing argument 3 for WooCommerce_PDF_Invoices_Export::reset_invoice_data() in wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-export.php on line 630
PHP Warning: Missing argument 4 for WooCommerce_PDF_Invoices_Export::reset_invoice_data() in wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-export.php on line 630
```

Can you help me?

Regards,
Alberto

**Comment by Spreeuw** [comment]
Hi Alberto,
Thanks for reporting. I had updated the code to work with the new filter for WCS 2.0, based on information the developer had sent me. He forgot to mention that they not only changed the name, but also changed the variables/arguments, and I didn't test (didn't have Subscriptions myself). I've been in contact with the developers again and they have supplied me with a development copy of 2.0.1 - expect a fix in a few hours from now!

Sorry for the inconvenience!

Ewout

**Comment by apalazzin** [comment]
Thanks for the support!
I'm looking forward to next changes.

**Comment by Spreeuw** [comment]
Hi Alberto,
I've comitted a fix ( f61f52f42fc73dc882dd6d9fd653326b0f271258 ), can you test this to confirm this fixes the behavior? Thanks!

Ewout

**Comment by Spreeuw** [comment]
I have just pushed version 1.5.24 to wordpress.org with this hotfix.

**Comment by apalazzin** [comment]
Ok, I'm testing new version.

**Comment by apalazzin** [comment]
Renewal Test: **FAILED**

I've clicked to complete my renewal order and **NONE** invoice produced.

**Comment by Spreeuw** [comment]
Hi Apalazzin,
That's very odd, do you get those same errors? I have checked the new filter and for as far as I can see, it matches the arguments and return value...
Is the email not sent at all, or is it just the attachment not added?
Did you [configure the plugin to attach to the renewal email](https://wordpress.org/support/topic/no-pdf-invoice-attaches-to-woo-subscription-order-renewal-via-paypal?replies=3)?

**Comment by apalazzin** [comment]
Hi @Spreeuw ,
no, no errors.

When I've clicked button "complete" on the renewal order:
* the order has been completed, but the invoice not produced
* the email "Your renewal order from 15/10/2015 is complete" has been sent without invoice attached

Now I've followed your link, added this code 
```
add_filter( 'wpo_wcpdf_email_allowed_statuses', 'wpo_wcpdf_subscription_renewal_invoice', 10, 1 );
function wpo_wcpdf_subscription_renewal_invoice ( $allowed_statuses ) {
    $subscription_statuses = array( 'customer_completed_renewal_order', 'customer_renewal_invoice' );
    return array_merge($allowed_statuses, $subscription_statuses);
}
```
in my ```function.php``` and scheduled new renewals.

**Comment by apalazzin** [comment]
All works!

My code in ```function.php```:
```
/**
 * Generate Invoice when subscription renewal and switch are completed
 */
add_filter( 'wpo_wcpdf_email_allowed_statuses', 'wpo_wcpdf_subscription_invoice', 10, 1 );
function wpo_wcpdf_subscription_invoice ( $allowed_statuses ) {
    // NB: exclude 'customer_renewal_invoice' because when the renewal order is FAILED, the Subscriptions plugin send the email "Invoice for renewal order with failed payment" and the invoice is generated
    $subscription_statuses = array( 'customer_completed_renewal_order', 'customer_completed_switch_order' );
    return array_merge($allowed_statuses, $subscription_statuses);
}
```

@Spreeuw  thanks for the support.

**Comment by apalazzin** [comment]
If you want, you can close this issue.

**Comment by Spreeuw** [comment]
Awesome, that's somewhat of a relief - I was afraid we'd have to do another hotfix release after I thought I finally got all the information I needed :)
Thanks for testing & your feedback!
