### ISSUE TITLE
Ability to set invoice notes before the document creation

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#104]
Currently it's only possible to add notes to the invoice after the document creation, but perhaps will be good to have that option available before the document existence. Currently affects customer using the "Keep PDF on server" setting, because if they add notes after the document creation they will not show in the PDF.

To go forward with this we need to save the notes to the order meta, and when the invoice exists transfer those to the document data. So, resuming, without document we use order meta, with document we use the document data.

Client ticket: https://secure.helpscout.net/conversation/1309507504/25901

@Spreeuw @Terminator-Barbapapa thoughts?

**Comment by Spreeuw** [comment]
@alexmigf can you describe a few different user workflows here?

What is the reason to store in 'order meta' vs 'document data' when it's all meta anyway? Is there anything against creating document data before the invoice number/date is created ?

**Comment by alexmigf** [comment]
With the current build:

### Scenario 1
It's not possible to add notes without having the invoice generated

### Scenario 2
Pro user has the setting "Keep PDF on server" enabled and won't see the notes on the PDF

### Scenario 3
Pro user has the setting "Keep PDF on server" enabled, changes the notes and can't see them updated on the PDF

### Scenario 4
User has a custom template, and if it doesn't updated it will not see the notes on the PDF

**Comment by Spreeuw** [comment]
These are how it currently works, but by workflows I meant expected scenarios that would happen in real life and how the plugin should work for those scenarios. Basically answering the questions:

1. When (at what point in the ordering/invoicing process) should it be possible to enter notes?
2. When can the user expect to see notes appear on the invoice?

**Comment by alexmigf** [comment]
### Scenario 1
Customer creates order but forgot to mention the VAT Number, asks by email or phone to add it, the Admin adds it to the invoice notes.

### Scenario 2
Admin has a local store and sells mainly in it's own country, but from time to time he receives orders from foreign countries. He needs to add some law information regarding those international invoices.

### Scenario 3
Admin has to indicate when the goods where made available to the client (in some countries is required)

### Scenario 4
Admin has to indicate some information regarding the products (defects, warranties, expiration date, lot number, etc)

### Scenario 5
Admin has to indicate some law informations regarding VAT/Taxes for specific products/clients

### Scenario 6
Admin has to indicate the Bank Account Details for a specific client/need

### Scenario 7
Admin has to indicate related Proforma number

### Scenario 8
Admin has to indicate the customer internal order request number/reference

**Comment by alexmigf** [comment]
It's working now, closing...
