### ISSUE TITLE
Add a preview document feature

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#113]
Would be good to have a preview document feature without the need of generating a document to see the changes.

**Comment by alexmigf** [comment]
@Terminator-Barbapapa suggested to use real data because user might need to add custom data and should be able to see how it looks in the document.

**Comment by alexmigf** [comment]
Do you prefer other location?

<img src="https://i.ibb.co/tcTcdwX/Captura-de-ecr-de-2020-11-02-13-04-22.png" alt="Captura-de-ecr-de-2020-11-02-13-04-22" border="0">

**Comment by Spreeuw** [comment]
closed by #335
