### ISSUE TITLE
Infinite Loop on Installation if $tmp_base is not writeable

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#117]
Line 501 of includes/class-wcpdf-main.php in init_tmp() checks if $tmp_base is a directory and if it isn’t, logs an error, but carries on processing.
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/8b233abe9bb09f145a46f14de4165a1ba8a675fa/includes/class-wcpdf-main.php#L502

This means that copy_fonts() is called on line 508, which calls get_tmp_path(), which checks for $tmp_base and if it’s not a directory, calls init_tmp(), which logs an error and calls copy_fonts(), which calls get_tmp_path() which calls init_tmp(), etc…
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/8b233abe9bb09f145a46f14de4165a1ba8a675fa/includes/class-wcpdf-main.php#L508

It would be useful if the installer could exit gracefully after the initial $tmp_base check on line 501 and let the user know that there’s a problem with their directory permissions, rather than locking the server in an infinite loop.

https://wordpress.org/support/topic/infinite-loop-on-installation-if-tmp_base-is-not-writeable/

**Comment by alexmigf** [comment]
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/tree/issue-117
