### ISSUE TITLE
Add line breaks support for Document Notes

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#121]
Replace line breaks with `<br>` for Document Notes.

<img src="https://i.ibb.co/Dw1ZvBg/Captura-de-ecr-de-2020-11-23-11-09-56.png" alt="Captura-de-ecr-de-2020-11-23-11-09-56" border="0">

**Comment by Spreeuw** [comment]
Your example screenshot is a bit confusing because it has `<br>` in it. The issue to be addressed is those notes _without_ `<br>`. Notes with `<br>` already work fine

**Comment by Spreeuw** [comment]
closed by 6228fbd
