### ISSUE TITLE
Mailpoet compatibility notice

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#123]
https://wordpress.org/support/topic/no-pdf-in-emails/

This is a recurring issue, covered in the Mailpoet documentation:
https://kb.mailpoet.com/article/292-choose-how-to-send-your-wordpress-websites-emails#attachments

> **Attachments are not permitted**
> When sending transactional emails with MailPoet 3 and the active sending method is MailPoet Sending Service, MailPoet does not include attachments in the emails that are sent because of bandwidth concerns and security implications with spam filters.
> We recommend to send links to files instead of attaching them to the email. If you need to send attachment for your WooCommerce or, disable this feature in MailPoet.
> 
> Meaning this option should be set to "**The default WordPress sending method**" (**NOT** selected in this screenshot):
> ![file-rXbF4BzOcB](https://user-images.githubusercontent.com/3217773/100459053-12fa0d80-30c5-11eb-81aa-510344b9f024.png)

If we can easily detect Mailpoet users that have this Mailpoet method selected, we should show a notice in the backend

**Comment by alexmigf** [comment]
I agree, nice one!
