### ISSUE TITLE
Try if Symfony Polyfill fixes missing characters if the MBString extension is disabled

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#125]
Try to test if the Symfony Polyfill library would solve the missing characters when the MBString extension is disabled. 

Pay attention that this library only supports PHP >= 7.1

Library: https://github.com/symfony/polyfill-mbstring
Example issue: https://wordpress.org/support/topic/german-characters-wrong-in-pdf-auo-umlaute/

**Comment by Spreeuw** [comment]
It looks like dompdf 1.0 may have added a new MB String function (`mb_substitute_character`), seeing this error:
https://wordpress.org/support/topic/error-when-changing-the-statue-of-an-order/
![02 11 2021-18 45](https://user-images.githubusercontent.com/3217773/107693006-d72b1900-6cad-11eb-92bc-cb2fd8d92f3d.png)

Yet another reason to bring in the polyfill. I'm not sure about how to best handle the PHP7.1 requirement though, that would mean we can't load it via composer and need to use our own autoloader for this and only load it for PHP7.1+.

**Comment by Spreeuw** [comment]
closed by #223
