### ISSUE TITLE
PHP8 compatibility

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#126]
The base plugin is PHP8.0 ready, but dompdf 0.8.3 (the currently bundled version) is not.

The reason we are not using 0.8.6 (latest release at the time of writing) is because it does not support PHP5.6 and PHP7.0, whereas 0.8.3 does. If we want to move forward and support PHP8.0, this means we have to drop support for PHP < 7.1.

I would like to propose a dual approach:

- Bundle the upcoming dompdf 1.0.0 (which will have PHP8.0 support) by default, but **only load it on PHP7.1+**. Creating PDF should be disabled elegantly. (e.g. no crashes/fatal errors, it should simply not try to create PDFs).
- Show an admin notice for sites using PHP < 7.1, linking to a wordpress.org plugin that replaces the bundled library the current 0.8.3 dompdf library
- The 0.8.3 dompdf plugin should show a notice that it's no longer needed as soon as the site has PHP7.1+

According to our plugin description we support PHP5.3 but David Anderson recently reported that is a false statement:

> I noticed, though, that even 0.8.3 says that it requires PHP 5.4+. Out of curiosity, I ran your current release through syntax checks on PHP 5.3 ...
> 
> ```
> # php -v
> PHP 5.3.3 (cli) (built: Nov 1 2019 12:28:08)
> Copyright (c) 1997-2010 The PHP Group
> Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
> 
> # find . -name '*\.php' -exec php -l {} \; | grep -v vendor/ | grep -v 'No syntax errors detected'
> PHP Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-frontend.ph
> p on line 100
> PHP Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-settings-do
> cuments.php on line 35
> PHP Fatal error: Can't use method return value in write context in ./includes/class-wcpdf-admin.php on
> line 375
> PHP Parse error: syntax error, unexpected '.', expecting ')' in ./vendor/composer/autoload_static.php o
> n line 23
> ```
> 
> Some of those errors are ones I recognise as being code that requires PHP 5.5+, so I ran it through 5.4 as well:
> 
> ```
> $ php54 -v
> PHP 5.4.45 (cli) (built: Oct 22 2019 13:23:07)
> Copyright (c) 1997-2014 The PHP Group
> Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
> $ find . -name '*\.php' -exec php54 -l
> {} \; | grep -v vendor/ | grep -v 'No syntax errors detected'
> PHP Parse error: syntax error, unexpected '.', expecting ')' in ./vendor/composer/autoload_st
> atic.php on line 23
> Parse error: syntax error, unexpected '.', expecting ')' in ./vendor/composer/autoload_static.
> php on line 23
> PHP Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-f
> rontend.php on line 100
> Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-fronte
> nd.php on line 100
> PHP Fatal error: Can't use method return value in write context in ./includes/class-wcpdf-adm
> in.php on line 375
> Fatal error: Can't use method return value in write context in ./includes/class-wcpdf-admin.ph
> p on line 375
> PHP Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-s
> ettings-documents.php on line 35
> Fatal error: Can't use function return value in write context in ./includes/class-wcpdf-settin
> gs-documents.php on line 35
> ```
> 
> If your autoload_static.php is getting run, it requires at least PHP 5.6:
> 
> ```
> $ php55 -v
> PHP 5.5.38 (cli) (built: Oct 22 2019 14:10:44)
> Copyright (c) 1997-2015 The PHP Group
> Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
> $ find . -name '*\.php' -exec php55 -l
> {} \; | grep -v vendor/ | grep -v 'No syntax errors detected'
> PHP Parse error: syntax error, unexpected '.', expecting ')' in ./vendor/composer/autoload_st
> atic.php on line 23
> Parse error: syntax error, unexpected '.', expecting ')' in ./vendor/composer/autoload_static.
> php on line 23
> ```

This means that in practice we already require PHP5.6 so the description should be updated to reflect this too.
The three `Can't use function return value in write context` errors can be fixed easily, but the `autoload_static.php` errors are harder. I don't know if/when this gets executed though.

Regardless, dropping 5.3 and later 5.6 support entirely is certainly not a bad thing.

**Comment by Spreeuw** [comment]
For tracking progress on dompdf 1.0.0: https://github.com/dompdf/dompdf/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0
And for beta testing we can use dompdf `master`, since the changes have been merged already: https://github.com/dompdf/dompdf/pull/2313

**Comment by Spreeuw** [comment]
Note that dompdf 0.8.6 (and 1.0.0) need slightly different options, see:

https://github.com/wpovernight/woocommerce-pdf-ips-dompdf-latest/blob/82702a407b2606f8ef2c84b16c4cfe52c5645e1e/woocommerce-pdf-ips-dompdf-latest.php#L42-L52

**Comment by alexmigf** [comment]
> For tracking progress on dompdf 1.0.0: [Milestone 1.0.0](https://github.com/dompdf/dompdf/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0)
> And for beta testing we can use dompdf `master`, since the changes have been merged already: [dompdf/dompdf#2313](https://github.com/dompdf/dompdf/pull/2313)

But it's in the branch `develop`: https://github.com/dompdf/dompdf/tree/develop

**Comment by alexmigf** [comment]
> Note that dompdf 0.8.6 (and 1.0.0) need slightly different options, see:
> 
> https://github.com/wpovernight/woocommerce-pdf-ips-dompdf-latest/blob/82702a407b2606f8ef2c84b16c4cfe52c5645e1e/woocommerce-pdf-ips-dompdf-latest.php#L42-L52

Options are the same.

**Comment by Spreeuw** [comment]
> 
> 
> > Note that dompdf 0.8.6 (and 1.0.0) need slightly different options, see:
> > https://github.com/wpovernight/woocommerce-pdf-ips-dompdf-latest/blob/82702a407b2606f8ef2c84b16c4cfe52c5645e1e/woocommerce-pdf-ips-dompdf-latest.php#L42-L52
> 
> Options properties are the same.

Nope - compare 0.8.3:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/6b4a418d9d477ccdb50f7c38e93bd0f2626e958e/includes/class-wcpdf-pdf-maker.php#L36-L46

Most notably the `chroot` option (which will be an array in 1.0.0 IIRC, still a string in 0.8.6). Without that images don't show.

> 
> But it's in the branch `develop`: https://github.com/dompdf/dompdf/tree/develop

Apologies, you're correct. Queued for master merge here: https://github.com/dompdf/dompdf/pull/2326

**Comment by alexmigf** [comment]
> Most notably the chroot option (which will be an array in 1.0.0 IIRC, still a string in 0.8.6). Without that images don't show.

They have a check for strings: https://github.com/dompdf/dompdf/blob/5cc66acdb00d8afbc4a5e680c69946c02c24378e/src/Options.php#L466-L473

**Comment by alexmigf** [comment]
> Most notably the chroot option (which will be an array in 1.0.0 IIRC, still a string in 0.8.6). Without that images don't show.

They have a check for string: https://github.com/dompdf/dompdf/blob/5cc66acdb00d8afbc4a5e680c69946c02c24378e/src/Options.php#L466-L473

**Comment by Spreeuw** [comment]
yes, but just for backwards compatibility. better to adhere to the new standard

**Comment by Spreeuw** [comment]
@alexmigf I was thinking that we should test this update when a filter for the tmp folder location is used to store these files outside of the shop base, because this _may_ (I didn't verify this!) affect that new `chroot` security option if that tmp folder does not fall below the `chroot` folder option

**Comment by alexmigf** [comment]
@Spreeuw  after reinstall fonts everything seems to works fine.

**Comment by alexmigf** [comment]
[Backwards compatibility with PHP 5.6 documentation](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/backwards-compatibility-with-php-5-6/)
