### ISSUE TITLE
Query in frontpage

### ISSUE THREAD

**Issue by Camilo517** [wpovernight/woocommerce-pdf-invoices-packing-slips#128]
Hello, this query is made in the frontpage, it should only be done for administrators and when visiting wp-admin

SELECT option_value
FROM 69gwsr_options
WHERE option_name = 'wpo_wcpdf_no_dir_error'
LIMIT 1

**Comment by Spreeuw** [comment]
reffering to this:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/f7c0832153b7dfa8cbfcca5d830dcea126345b8c/includes/class-wcpdf-main.php#L60-L68

@alexmigf I agree that we should limit this to the admin. Perhaps you can move that check into the `admin_notice` hook itself?
