### ISSUE TITLE
Please add a description and website here at github

### ISSUE THREAD

**Issue by jnachtigall** [wpovernight/woocommerce-pdf-invoices-packing-slips#13]
![auswahl_059](https://cloud.githubusercontent.com/assets/3307404/11730251/1d48159c-9f94-11e5-9251-ded19d25f40b.png)

**Comment by wpovernight** [comment]
Done! Just curious - what do you use this for?

**Comment by jnachtigall** [comment]
I am just a user. When I find an error (or small issue) I do report it, if possible with a patch. Before reporting I always try to locate the problem myself in the code.

While reporting another issue, I think I had problem locating this repo (and not confusing it with the svn wordpress sync repro). I think FOSS benefits from making clear where the source is.

**Comment by Spreeuw** [comment]
Much appreciated, thanks!
