### ISSUE TITLE
Replace all wc_date_format() with custom function

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#132]
@Spreeuw said:

> Maybe we should introduce our own date formatting function for easier filtering, where we can pass a `$type` variable. Then we replace all our `wc_date_format( $date )` calls with `wcpdf_date_format( $date, $type )`  with a filter that includes both arguments.

https://wpovernight.slack.com/archives/C0121KYKGN6/p1611576680007100

Ticket: https://secure.helpscout.net/conversation/1405634973/28262?folderId=221726

**Comment by alexmigf** [comment]
@Spreeuw `wc_date_format` doesn't take arguments, shouldn't we follow the same path and do like this?

```php
function wcpdf_date_format( $date_type = null ) {
	return apply_filters( 'wpo_wcpdf_date_format', wc_date_format(), $date_type );
}
```

**Comment by Spreeuw** [comment]
Yes, my bad. `wc_date_format` doesn't format the date, it simply returns the format and we should do the same.

**Comment by alexmigf** [comment]
What should be the filter name, since we already have one called `wpo_wcpdf_date_format` here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/b80fc5f9bca714439494a6de89846b60123219f9/includes/documents/abstract-wcpdf-order-document-methods.php#L1206

**Comment by Spreeuw** [comment]
renaming is not going to help if people already hooked that filter.
We could keep the same name and simply add an extra parameter. So:
```php
apply_filters( 'wpo_wcpdf_date_format', wc_date_format(), $this )
```

becomes

```php
wcpdf_date_format( $this, 'document' )
```

(if you have any better suggestions for `document`, be my guest... 🤷‍♂️ )

**Comment by alexmigf** [comment]
Initially I was think more like this:

```php
/**
 * Date formatting function
 *
 * @param  string $date_type Optional. A date type to be filtered eg. 'invoice_date', 'date_created', 'date_modified', 'order_date', 'date_paid', 'date_completed', 'current_date'.
 */
function wcpdf_date_format( string $date_type = null ) {
	return apply_filters( 'wpo_wcpdf_date_format', wc_date_format(), $date_type );
}
```

But I can add an object argument set to null too. What you think?

**Comment by Spreeuw** [comment]
yes, setting to null makes it a bit more flexible. Is there a specific reason you're typecasting? (since we don't do that anywhere else in the plugin yet)

**Comment by alexmigf** [comment]
No particular reason, I will remove.

**Comment by Spreeuw** [comment]
your comment states:
```
'invoice_date', 'date_created', 'date_modified'
```
but I wonder if we should prefix the order dates here (e.g. `order_date_created` etc.) to avoid confusion

**Comment by alexmigf** [comment]
I used the same names from placeholders, but I will fix that.
