### ISSUE TITLE
Create universal document data functions

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#133]
Third party documents as well as our own Professional extension documents currently need to 'reinvent the wheel' by writing their own code to create all the input fields and buttons to be shown on the "PDF Document data" tab.

If we use the code from `\WPO\WC\PDF_Invoices_Pro\Writepanels::output_number_date_edit_fields()` in the Professional extension and update it to the standards currently applied in rendering the Invoice fields, this can be reused by other plugins.

To facilitate this reuse, we can include the class instance as a second parameter in the `wpo_wcpdf_meta_box_end` action, making it super easy to call the function. Likewise, we can add an additional action inside the `save_invoice_number_date()` method, passing the required data as well as the class instance.

Some fields (like document notes etc.) should be made optional in the field rendering function.

We can use our own Professional extension as a test case.

**Comment by alexmigf** [comment]
Not finished yet, needs better testing.
