### ISSUE TITLE
Invoice Notes issues

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#136]
# Notes
Notes seem to behave strangely, but comparing to the current release I think that it already broke before these changes.

If I enter this:
```
\\ %20
\n
/
"text"
<div>some html</div>
``` 

I get different results depending on whether I save via "Regenerate" or via saving the order:
**Regenerate:**
```
\\ <br />
\n<br />
/<br />
"text"<br />
some html
```
**save:**
```
\\\\ <br />
\\n<br />
/<br />
\"text\"<br />
some html
```

I believe we discussed this before so I don't know if this is a regression or if we decided to always convert to `<br>`, but some of this is still buggy, also the fact that it's not handled the same between saving and regenerating.

**Comment by alexmigf** [comment]
0f8c580f3578dec5bfe7b44c098eb45f1bbb6030

**Comment by alexmigf** [comment]
@Spreeuw do you want to keep the `<br>`s?

**Comment by Spreeuw** [comment]
What the user inputs is what should be shown on the fields. So if the user inputs `<br>` it should show `<br>` in the field. If the user adds a line break it should show a line break.
