### ISSUE TITLE
Add action hook to header function

### ISSUE THREAD

**Issue by dpeyou** [wpovernight/woocommerce-pdf-invoices-packing-slips#138]
Add the 200 OK header to this section: https://ideone.com/eOBcPP

The problem is that the "OK" header is not being sent along for the "download" action.

**Comment by Spreeuw** [comment]
@dpeyou the proposal from your link is to add an action hook (rather than the header), see line 22:
```php
do_action('wpo_wcpdf_headers', $filename, $mode, $pdf);
```
WP already sends the 200 OK header but if plugins break this (which in the case reported was BuddyBoss Platform, a Boddypress fork), the action hook allows overriding that.
