### ISSUE TITLE
Simple template alignment issue in totals

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#139]
Reported here: https://wordpress.org/support/topic/after-update-to-2-8-0-the-totals-part-is-misaligned/?view=all

This seems to be happening after updating to 2.8.0+

<img src="https://i.ibb.co/gvRpRX8/Captura-de-ecr-de-2021-02-04-11-35-42.png" alt="Captura-de-ecr-de-2021-02-04-11-35-42" border="0">

**Comment by Spreeuw** [comment]
Here's a few tests I ran. To present the issue clearly I used the following filter to generate a long text for the second totals column:
```php
add_filter( 'wpo_wcpdf_woocommerce_totals', 'wpo_wcpdf_custom_totals', 10, 3 );
function wpo_wcpdf_custom_totals ($totals, $order, $document_type) {
	$totals['testing'] = array(
		'label' => 'Test',
		'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dolor purus, porta sit amet condimentum convallis, tincidunt ut dui.',
	);
	return $totals;
}
```

# Test 1: REMOVING these width styles for both columns:
(effectively leaving it up to dompdf to determine the width)
```css
table.totals th.description,
table.totals td.price {
	width: 50%;
}
```
**Result: No effect**
![second-page-totals-issue-test-1](https://user-images.githubusercontent.com/3217773/107010572-cc94ef00-6796-11eb-891f-5dea7b143cf6.png)


# Test 2: Align values right
adding:
```css
table.totals td.price {
	text-align: right!important;
}
```
**Result: Seems to prevent run-in but still has broken alignment.**
![second-page-totals-issue-test-2](https://user-images.githubusercontent.com/3217773/107010610-d9b1de00-6796-11eb-9d43-63811c5d8d7d.png)
# Test 3: Move totals to separate table
This is what we do in the Simple Premium template. Changing this:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/a381086bced701aae757c87d6626fef3d6ad725e/templates/Simple/invoice.php#L117-L151

To this:
```php
<table class="notes-totals">
	<tbody>
		<tr class="no-borders">
			<td class="no-borders" style="width:60%">
				<div class="document-notes">
					<?php do_action( 'wpo_wcpdf_before_document_notes', $this->type, $this->order ); ?>
					<?php if ( $this->get_document_notes() ) : ?>
						<h3><?php _e( 'Notes', 'woocommerce-pdf-invoices-packing-slips' ); ?></h3>
						<?php $this->document_notes(); ?>
					<?php endif; ?>
					<?php do_action( 'wpo_wcpdf_after_document_notes', $this->type, $this->order ); ?>
				</div>
				<div class="customer-notes">
					<?php do_action( 'wpo_wcpdf_before_customer_notes', $this->type, $this->order ); ?>
					<?php if ( $this->get_shipping_notes() ) : ?>
						<h3><?php _e( 'Customer Notes', 'woocommerce-pdf-invoices-packing-slips' ); ?></h3>
						<?php $this->shipping_notes(); ?>
					<?php endif; ?>
					<?php do_action( 'wpo_wcpdf_after_customer_notes', $this->type, $this->order ); ?>
				</div>				
			</td>
			<td class="no-borders"  style="width:40%">
				<table class="totals">
					<tbody>
						<?php foreach( $this->get_woocommerce_totals() as $key => $total ) : ?>
						<tr class="<?php echo $key; ?>">
							<th class="description"><?php echo $total['label']; ?></th>
							<td class="price"><span class="totals-price"><?php echo $total['value']; ?></span></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>
```

Appears to solve the issue **as long as the table doesn't start on the first page**.
With rows on the second page it looks fine:
![second-page-totals-issue-test-6](https://user-images.githubusercontent.com/3217773/107013120-3c58a900-679a-11eb-961e-528c4fb8a166.png)
But when starting on the first page (but printed on the second):
![second-page-totals-issue-test-7](https://user-images.githubusercontent.com/3217773/107013160-48dd0180-679a-11eb-9ac7-5b132001ca39.png)
