### ISSUE TITLE
Deployment Script tries to CHMOD nonexistent .htaccess file and fails

### ISSUE THREAD

**Issue by ianbmacdonald** [wpovernight/woocommerce-pdf-invoices-packing-slips#146]
We just recently tried to upgrade to the latest versin of the plugin 2.8.2 and discovered what appears to be a missing download of an .htaccess file in the deployment script after reviewing our ftpsockets log. 

Below are the transcripts for the correctly deployed .gitignore file, and the failing .htaccess file

In the first transcript, we see the download of .gitignore to the upgrade folder:
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "RETR /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"

Followed by the STOR to copy it to the final plugin location with a CHMOD to set permissions there
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "STOR /usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "SITE CHMOD 674 /usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"

In the second transcript, the .htaccess file is not downloaded and copied, so the change of working directory and following CHMOD command just fails and aborts the installation of the plugin. 

Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "CWD /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "550 Failed to change directory."

Working Deployement of .gitignore:
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "TYPE A"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "200 Switching to ASCII mode."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PASV"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,88,76)."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "NLST /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "150 Here comes the directory listing."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "226 Directory send OK."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "TYPE I"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "200 Switching to Binary mode."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PASV"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,144,199)."
**Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "RETR /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"**
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "150 Opening BINARY mode data connection for /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore (51 bytes)."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] OK DOWNLOAD: Client "127.0.0.1", "/usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore", 51 bytes, 65.45Kbyte/sec
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "226 Transfer complete."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PASV"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,186,40)."
**Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "STOR /usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"**
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "150 Ok to send data."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] OK UPLOAD: Client "127.0.0.1", "/usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore", 51 bytes, 57.05Kbyte/sec
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "226 Transfer complete."
**Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "SITE CHMOD 674 /usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore"**
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] OK CHMOD: Client "127.0.0.1", "/usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.gitignore 674"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "200 SITE CHMOD command ok."

Failing deployment of .htaccess 
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "TYPE A"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "200 Switching to ASCII mode."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PASV"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,183,155)."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "NLST /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "150 Here comes the directory listing."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "226 Directory send OK."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PWD"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "257 "/usr/share/wordpress" is the current directory"
**Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "CWD /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "550 Failed to change directory."**
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "SITE CHMOD 674 /usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "550 SITE CHMOD command failed."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FAIL CHMOD: Client "127.0.0.1", "/usr/share/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess 674"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PASV"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "227 Entering Passive Mode (127,0,0,1,177,6)."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "NLST /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "150 Here comes the directory listing."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "226 Directory send OK."
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "PWD"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "257 "/usr/share/wordpress" is the current directory"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP command: Client "127.0.0.1", "CWD /usr/share/wordpress/wp-content/upgrade/woocommerce-pdf-invoices-packing-slips.2.8.2-2/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-font-lib/.htaccess"
Sat Feb  6 16:36:17 2021 [pid 30379] [ftpsecure] FTP response: Client "127.0.0.1", "550 Failed to change directory."

**Comment by ianbmacdonald** [comment]
It is worth noting that this initially failed to upgrade in one of our environments, so we repeated the failure in other environments, and then completely purged and attempted a new installation to capture the error scenario cleanly and rule out any cruft from older versions.

**Comment by ianbmacdonald** [comment]
Noting the modification date is 2017 on this .htaccess file and it simply contains a commented line, I am wondering if it (and other git related hiddent files) was included in the package in err.   Simply removing it and uploading the plugin manually, rather then via the store works around this issue for now.

**Comment by Spreeuw** [comment]
Thanks for reporting! Can you share your deployment script with us? This is not a known issue to us since most people install directly by either:

1. Installing directly via the WordPress plugin search
2. Downloading the package zip file and installing it via WordPress (Plugins > Add New > Upload)
3. Downloading the zip and uploading the contects of the ZIP via ftp

If you can share a bit more details of your deployment process (and the deployment script you mention) we can try to find why you're getting that error.

**Comment by Terminator-Barbapapa** [comment]
Since this has no replies for several years I'm closing this issue for now.
