### ISSUE TITLE
Create new store tables in DB for each year if reset setting enabled

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#149]
@Spreeuw said:

> It seems a fair number of people have recently reported issues with the yearly number reset. It's a tough problem to tackle because there is no straight forward way to reliably handle sequential numbers for previous years. Last year we introduced an 'easier' setting that allows people to set the invoice date to the order date (previously the only way to do that was via a filter), and this is what's causing the issues because the generation of invoices is no longer truly sequential. So people could generate invoices for this year, then invoice for last year (triggering a reset) then invoices for this year again (triggering another reset, etc.)
This afternoon I was thinking about possible solutions and I wonder if making year-based store-tables is a solution here..
In this case, the plugin would suffix the store name (e.g. invoice_number ) with the year of the document ( so invoice_number_2021 for an invoice from 2021) As a result, rather than resetting the current store, it would simply move to a new, empty store (automatically!) as soon as the new year starts. And then, when an invoice is made for last year, it simply appends a row to last year's store (invoice_number_2020)
This will probably require a DB migration, but may be the most reliable option that we have.

> Migration shouldn't be too difficult, basically we only need to rename the table upon upgrading.
This will need thorough testing of course since it's such a vital part of the plugin... We also need to think about the scenario where people switch on or switch off the reset option and how this is handled internally (keeping the existing 'next invoice number' in tact).

Discussion: https://wpovernight.slack.com/archives/C0121KYKGN6/p1613149015029400

**Comment by alexmigf** [comment]
> We also need to think about the scenario where people switch on or switch off the reset option and how this is handled internally (keeping the existing 'next invoice number' in tact).

We keep using the store tables with the year, and when the reset is 'on' he starts from 1 and when is 'off' it continues in the new table from the last year table number + 1?

**Comment by Spreeuw** [comment]
Sounds like a good idea, though in that case we should not use the invoice year (document year) for selecting the table but the 'current' year.
We could unify this with the `wpo_wcpdf_reset_number_yearly_start` filter, as that will also require a different approach. That method uses the document object, so to prevent breaking changes we should pass that to the number store class.

A different approach would be not to change the store name but to handle the table name internally, but a (possible) downside to that is that the 'number store' because much more dependent on the document, whereas in the design I tried to keep it as abstract as possible.

**Comment by alexmigf** [comment]
Seeing your comments, I believe you want to pass the `store_name` with the year appended. So, for the year comparison I was thinking on checking the current table for the last row date, and if is null check if we have a prior year table and get the highest ID, something like this:

```php
public function get_last_date( $format = 'Y-m-d H:i:s' ) {
	global $wpdb;
	if( ! empty( $table_name ) ) {
		$row = $wpdb->get_row( "SELECT * FROM {$this->table_name} WHERE id = ( SELECT MAX(id) from {$this->table_name} )" );
		$date = isset( $row->date ) ? $row->date : null;
		if( ! is_null($date) ) {
			$formatted_date = date( $format, strtotime( $date ) );
		} else {
			$formatted_date = null;
		}
		return $formatted_date;
	} else {
		return null;
	}
}

public function get_last_number_from_last_year() {
	global $wpdb;
	$last_number_year = $this->get_last_date( 'Y' );
	if( empty( $last_number_year ) && isset( $this->document->settings['reset_number_yearly'] ) ) {
		$store_name_without_year = preg_replace( '/[0-9]+/', '', $this->store_name );
		$last_year               = date( 'Y' ) - 1;
		$last_year_table_name    = "{$wpdb->prefix}wcpdf_{$store_name_without_year}{$last_year}";

		// check if last year table exists
		if( $wpdb->get_var("SHOW TABLES LIKE '{$last_year_table_name}'") == $last_year_table_name) {
			$number = $wpdb->get_row( "SELECT MAX(id) from {$last_year_table_name}" );
		}
	}
}
```

**Comment by Spreeuw** [comment]
It's difficult for me to comment on this without seeing how these functions are integrated within the rest of the class

**Comment by alexmigf** [comment]
* Check if we have document date
* If we don't have document date, try to find the current store table and get it's name (maybe with a static function)
* Initiate the store number class object with the correct name
* Check for year reset by checking the last number date:
    - If reset 'on' and last number date 'null': new year started, number starts from 1
    - If reset 'off' and last number date 'null': new year started, starts from previous year table last number
    - If reset 'on/off' and last number date 'not null': year ongoing, continue with auto-increment
* Set the correct number

**Comment by Spreeuw** [comment]
I think there are 3 key elements in this:

1. Table selection (based on whether it should be reset yearly)
2. Table initiation (when the 'current/document year' is not available yet or when it is first created)
3. Determining first number for table initiation (continuing from last year's table, resetting to 1 or resetting to another preset/filtered value)

I see two possible approaches:

## 1. Handling store selection and resets from the document class calling it
This is basically an alternative approach to the methods currently in place, with the primary difference being not 'resetting' the next number, but selecting the appropriate store first and setting it with the first number if it didn't exist yet.

The core key component here would be a function that returns a store name based on:
1. Date (year)
2. Whether reset numbers is enabled.

An example scenario for reset enabled and for reset disabled ('order date' used as invoice date) looks like this:

1. Document is created
2. Date is set (e.g. 2020-12-30)
3. Function is called checking if a store is available:
    - a) When reset is ON, it uses the **document date** for the store (e.g. `invoice_number_2020`)
    - b) When reset is OFF, it uses the **current date** for the store (e.g. `invoice_number_2021`)
    - If the store does not exist yet, it inits (instantiates) the store and immediately sets the next number to last year's store's next number (reset OFF) or 1 / the `wpo_wcpdf_reset_number_yearly_start` filtered value (reset ON)
    - Store name is returned
4. Number_Store can be instantiated (or the instance could even have been returned by the above function/method)
5. document number is created via the current `increment` method, just like before

## 2. Handling store selection and resets from within the Number_Store class
This is a bigger redesign of the current architecture and adds more functionality (and dependency) specifically related to the document settings and data and will require passing the document object to it.

All 'reset' (`set_next()`) code is removed from the document class and the Number Store class determines what table to use and how to initiate it.

Example scenario:
1. Document is created
2. Date is set (e.g. 2020-12-30)
3. Number store is instantiated (`invoice_number`)
    - a) When reset is ON, it appends the year of **document date** to the store name (e.g. `_2020`) during construct
    - b) When reset is OFF, it appends the year of **current date** to the store name (e.g. `_2021`) during construct
    - An additional call to the `set_next` method is added at the end of the current `init` method, setting the next number to last year's store's next number (reset OFF) or 1 / the `wpo_wcpdf_reset_number_yearly_start` filtered value (reset ON)

**Comment by alexmigf** [comment]
> b) When reset is OFF, it uses the current date for the store (e.g. invoice_number_2021)

I think we have a problem here, because in this scenario if the year changes we want to keep the numeration from last year, and in this case can't be `increment`, or I'm missing something?

**Comment by Spreeuw** [comment]
This is independent from the store selection itself, it merely affects the initialization of the store, which is mentioned right below that part you quoted (emphasis on the part that I think addresses your concern):

> If the store does not exist yet, it inits (instantiates) the store and immediately **sets the next number to last year's store's next number (reset OFF)** or 1 / the wpo_wcpdf_reset_number_yearly_start filtered value (reset ON)

**Comment by Spreeuw** [comment]
Any further thoughts about approach 1 vs 2? Or an "approach 3"?
