### ISSUE TITLE
Quantity fields on pdfs not reflecting returns

### ISSUE THREAD

**Issue by underwd** [wpovernight/woocommerce-pdf-invoices-packing-slips#15]
Scenario:
Customer places an order for 10 widgets, later decides he wants to return 4 of them.

Admin refunds 4 widgets on the backend which changes quantity from 10 to 6.  

Now, if a PDF is generated, the quantity field displays 10 instead of 6.  (Order total is not updated either.)

(WC 2.5.5, WP 4.5.1 Running Storefront theme.)

**Comment by underwd** [comment]
Found that this feature is enabled by design.

**Comment by Spreeuw** [comment]
https://wordpress.org/support/topic/quantities-in-packing-slip-not-right-after-refund?replies=2
