### ISSUE TITLE
Add Dirham symbol to our currency font

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#151]
Ticket: https://secure.helpscout.net/conversation/1427114261/28810/

Font: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/vendor/dompdf/dompdf/lib/fonts/currencies.ttf

**Comment by Spreeuw** [comment]
UAE would be good to have too https://wordpress.org/support/topic/text-overlap-in-pdf-invoice/
(though I was under the assumption INR is already included)

**Comment by YordanSoares** [comment]
@Spreeuw realized that adding the dirham characters will not work, as dompdf does not support RTL languages. So @Spreeuw proposed to use the currency code ([ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)) instead: AED.

**Comment by YordanSoares** [comment]
I performed research about the currencies that are written using RTL script, and found the next ones:

- AED: United Arab Emirates dirham [3 characters] (د.إ)
- BHD: Bahraini Dinar [3 characters] (د.ب)
- DZD: Algerian Dinar [2 characters] (دج)
- IQD: Iraqi Dinar [3 characters] (ع.د)
- IRR: Iranian Rial [1 character] (﷼)
- JOD: Jordanian Dinar [3 characters] (د.ا)
- KWD: Kuwaiti Dinar [3 characters] (د.ك)
- LBP: Lebanese Pound [3 characters] (ل.ل)
- LYD: Libyan Dinar	[3 characters] (ل.د)
- MAD: Moroccan Dirham [4 characters] (د.م.)
- MVR: Rufiyaa [2 characters] (.ރ)
- OMR: Rial Omani [4 characters] (ر.ع.)
- QAR: Qatari Riyal	[3 characters] (ر.ق)
- SAR: Saudi Riyal	[3 characters] (ر.س)
- SYP: Syrian Pound [3 characters] (ل.س)
- TND: Tunisian Dinar [3 characters] (د.ت)
- YER: Yemeni Rial [1 characters] (﷼)

So, following the proposal of @Spreeuw, we could use a code as the following to display the three code letter as a fallback in the dompdf:

```php
add_action( 'wpo_wcpdf_before_html', function ( $document_type, $document ) {
	add_filter( 'woocommerce_currency_symbol','wpo_wcpdf_currency_symbol_text', 999, 2);
}, 10, 2 );
add_action( 'wpo_wcpdf_after_html', function ( $document_type, $document ) {
	remove_filter( 'woocommerce_currency_symbol','wpo_wcpdf_currency_symbol_text', 999, 2);
}, 10, 2 );
function wpo_wcpdf_currency_symbol_text( $currency_symbol, $currency ) {
	if ( in_array( $currency, [ 'AED', 'BHD', 'DZD', 'IQD', 'IRR', 'JOD', 'KWD', 'LBP', 'LYD', 'MAD', 'MVR', 'OMR', 'QAR', 'SAR', 'SYP', 'TND', 'YER' ] ) ) {
		$currency_symbol = $currency;
	}
	return $currency_symbol;
}
```

**Comment by madatr** [comment]
Please implement this soon. Doesn't seem too hard but the result is currently unprofessional

<img width="350" alt="Screenshot 2021-12-16 at 14 55 14" src="https://user-images.githubusercontent.com/45605051/146375932-0ddbcafc-7505-4105-b0c8-8809a659f62e.png">
t

**Comment by Spreeuw** [comment]
@madatr have you tried the suggestion above? https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/151#issuecomment-841775506

If you need RTL support you can use the mpdf extension: https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/releases
