### ISSUE TITLE
Warn the user when the logo is bigger than necessary.

### ISSUE THREAD

**Issue by dpeyou** [wpovernight/woocommerce-pdf-invoices-packing-slips#155]
Maybe the warning needs to be created for images above 600dpi..?

**Comment by dpeyou** [comment]
@Spreeuw what type of warning do we want to show? Do you want it to look like the ads or activation notices that appear at the top/bottom of pages or some text next to the setting itself?

![Screenshot from 2021-10-20 15-03-24](https://user-images.githubusercontent.com/74280840/138163716-168cffb0-c247-4bac-852d-6265d2260280.png)

**Comment by Spreeuw** [comment]
@dpeyou you didn't write anything about the context of this issue (or the reason to do this), but I would do an inline error (not at the top of the page), using the WP classes `notice notice-warning inline` . I would also make the message itself a bit more informative/explicit.
