### ISSUE TITLE
Update Portuguese locales with recent strings

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#158]
Update Portuguese locales with recent strings.

**Comment by alexmigf** [comment]
@YordanSoares can you update with automatic translations for revision?

**Comment by Spreeuw** [comment]
@alexmigf you are already PTE for the official language pack!
https://translate.wordpress.org/locale/pt/default/wp-plugins/woocommerce-pdf-invoices-packing-slips/

**Comment by alexmigf** [comment]
I believe I already was.

**Comment by YordanSoares** [comment]
@alexmigf I left you the translations for revision here: https://wpovernight.slack.com/archives/C0121KYKGN6/p1621959248007100?thread_ts=1621951045.002600&cid=C0121KYKGN6. There you find the remaining and fuzzy strings for both `pt_BR` and `pt_PT`. After reviewing, you can import the .po files here:
- [Importer for Portuguese (Brazil)](https://translate.wordpress.org/projects/wp-plugins/woocommerce-pdf-invoices-packing-slips/dev/pt-br/default/import-translations/)
- [Importer for Portuguese (Portugal)](https://translate.wordpress.org/projects/wp-plugins/woocommerce-pdf-invoices-packing-slips/dev/pt/default/import-translations/)

@Spreeuw in the case of the locales in which we have PTE capabilities to keep them updates, this is no longer necessary.

**Comment by alexmigf** [comment]
Done!
