### ISSUE TITLE
Allow 'wcpdf_date_format' function to format time too

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#162]
Currently this function only supports date format.

Suggestion from @Spreeuw here: #32 (comment)

Should replace the wc_date_format() and wc_time_format().

**Comment by Spreeuw** [comment]
If we're going to do time formatting specifically for PDF invoices, I would suggest to create a new function instead of trying to do it with `wcpdf_date_format()`
