### ISSUE TITLE
Using ' or " in document notes adds backslashes

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#172]
Using ' or " in document notes adds backslashes:

![Captura de ecrã de 2021-04-20 11-15-51](https://user-images.githubusercontent.com/533273/115379810-cb863200-a1c9-11eb-93eb-474192f65b59.png)

Reported here: https://secure.helpscout.net/conversation/1462166150/29712/#thread-4321348254

**Comment by Spreeuw** [comment]
duplicate? https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/136

**Comment by alexmigf** [comment]
I thought that was closed already :facepalm:

**Comment by alexmigf** [comment]
Yes, it fixes this, closing...
