### ISSUE TITLE
Improve internationalization of the plugin (i18n)

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#177]
- [ ] Add numbered placeholders.
- [ ] Add comments for translators.

**Comment by Spreeuw** [comment]
@YordanSoares I closed this but I was preparing a new release and realized that the POT and bundled PO/MO translations have not been updated yet. I think we should do this before releasing, can you do that? (perhaps open a new issue/PR)

**Comment by YordanSoares** [comment]
Sure @Spreeuw! It's done: #181
