### ISSUE TITLE
Why is this meta '_wcpdf_formatted_invoice_number' only get updated once?

### ISSUE THREAD

**Issue by khaiknievel** [wpovernight/woocommerce-pdf-invoices-packing-slips#18]
Ola, 

I was wondering why the mentioned meta key is only stored once at [class-wcpdf-export.php#L699](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-export.php#L699)

Is there any particular reason to this?

**Comment by Spreeuw** [comment]
Not by design. For completeness sake it should also be stored when the number is altered during save_post:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-writepanels.php#L340-L341

**Comment by khaiknievel** [comment]
Gotcha.
