### ISSUE TITLE
VAT on invoice

### ISSUE THREAD

**Issue by katiasmet-studiohyperdrive** [wpovernight/woocommerce-pdf-invoices-packing-slips#188]
Hi

How can I show the right VAT on the invoice? In July it is mandatory to show VAT on all EU invoices. We set al the taxes and VAT in Woocommerce. Product prices are VAT included, prices in the shop are included VAT, in the basket VAT excluded.

Settings Woocommerce Taxes:
<img width="690" alt="Screenshot 2021-06-11 at 21 50 57" src="https://user-images.githubusercontent.com/77779038/121741805-4a7b5500-caff-11eb-9fd7-ed173f4015f1.png">

Example invoice:
<img width="668" alt="Screenshot 2021-06-11 at 21 51 53" src="https://user-images.githubusercontent.com/77779038/121741830-523af980-caff-11eb-8127-0ce00946c57f.png">

It is a website with subscriptions, so the orders could be older. Maybe that's why we can't see the VAT?

Woocommerce: 5.0.0
Woocommerce Subscriptions: 3.0.12
WooCommerce PDF Invoices & Packing Slips: 2.8.3

Thanks!
Katia

**Comment by Spreeuw** [comment]
It's indeed possible that the older orders didn't have the tax yet. We have some documentation on the subject here:
https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/displaying-taxes/#taxes-missing

If you still have unanswered questions after reading that, please open a topic in our support forum here:
https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips/
