### ISSUE TITLE
How can i sent email to customer with pdf attchment when place order?

### ISSUE THREAD

**Issue by himansu9385** [wpovernight/woocommerce-pdf-invoices-packing-slips#19]
Hello Sir,

Thanks in advance 

How can i sent email to customer with pdf attchment when place order?

I need to send pdf with customer emails also when placing any order.

**Comment by Spreeuw** [comment]
Please use the [support forum](https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips/) for questions! You can find the attachment settings under WooCommerce > PDF Invoices > General:
![schermafbeelding 2017-04-07 om 10 06 56](https://cloud.githubusercontent.com/assets/3217773/24791322/fa0d9fee-1b79-11e7-95f2-1445dfaadf01.png)
