### ISSUE TITLE
nested ob_start calls in the code cause printing templates to screen instead of returning

### ISSUE THREAD

**Issue by javorszky** [wpovernight/woocommerce-pdf-invoices-packing-slips#20]
When inserting the Simple template's css, the code uses output buffering here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-functions.php#L38-L42

That's called when processing the template, which is a [call from within `generate_pdf`](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-export.php#L383), which calls `process_template`, which [calls `get_template`](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-export.php#L294), which also have output buffering.

Even though the [php docs on output buffering](http://uk1.php.net/manual/en/function.ob-start.php) say that one can nest buffering, this doesn't seem to be the case, as any output call (such as an `echo` or an `ob_get_clean`) would trigger an implicit flush, sending the contents to the browser instead of holding on to the content in a variable.

**Comment by Spreeuw** [comment]
Hi! Thanks for the feedback. This code has been like this for several years now without any issues, even including `echo` calls. Which PHP version do you use? Do you have an alternative solution?

Please note that this code will be deprecated in a few weeks, check the development branch here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/tree/2.0-rewrite

**Comment by javorszky** [comment]
Hullo,

I'm using php 7.1.5 (whatever the latest homebrew version is), I don't really do any different configuration from the default. As the dev environment it's Laravel Valet.

I think the reason it didn't cause a problem because either the file is given to the user through ajax, or is being saved to the server with no user interaction, so there's nowhere to flush the buffer.

I've worked around it by using `file_get_contents` instead of `ob_start` and `ob_get_clean`. That also means that the global `$wpo_wcpdf` at the top of the css files (like here https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/templates/pdf/Simple/style.css#L1) won't parse, but the rest of the file isn't using it anyway, so it doesn't matter.

I'll check out the dev branch. It'd be awesome to generate pdf files without my `debug.log` getting filled with notices. I've seen the topic on the wp.org support forum about it :).

**Comment by Spreeuw** [comment]
Which thread on the support forum is that? I have seen PHP7.1 related posts but I think those were DomPDF issues (0.6 is not very 7.0 or 7.1 friendly).

The new version is a complete rewrite and doesn't use the $wpo_wcpdf global anymore. (it does have a legacy mode to support old templates that do use it though). It also uses the latest DOMPDF, 0.8.
I'm doing ob_start / ob_get_clean because it's useful to be able to use PHP variables in the CSS file (like a reference to the template base path, for example when using custom fonts).

**Comment by javorszky** [comment]
This one: https://wordpress.org/support/topic/php-error-a-non-numeric-value-encountered/

Fair point about using the `ob_start`. Hm... I'll see if I can come up with something that would allow not to do implicit flushes. There's the function [`ob_implicit_flush`](http://uk1.php.net/manual/en/function.ob-implicit-flush.php), maybe that's all that's needed for it. I'll report back shortly.

**Comment by javorszky** [comment]
Okay, I quite literally have no idea why it works now, but for the life of me I can't reproduce the issue I had with it even after reinstating the nested output buffering.

**Comment by Spreeuw** [comment]
No worries! The [issue](https://wordpress.org/support/topic/php-error-a-non-numeric-value-encountered/) you referred to earlier is DOMPDF related AFAIK and most likely solved in the 2.0 branch.
Any feedback on that branch is more than welcome by the way!
