### ISSUE TITLE
Shop address is gone after disable WPML

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#206]
Steps to reproduce:

1. Disable test mode
2. Set different shop address per WPML languages
3. Create a PDF
4. Disable WPML
5. Shop address is gone

The [function](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/ad00074337c9e9799a4f00b450543d7a59660fac/includes/documents/abstract-wcpdf-order-document.php#L622-L627) looks for the `default` but should be empty at this stage.

**Comment by alexmigf** [comment]
@Spreeuw maybe we should first check if `wcpdf_order_locale` is set and use that first? And then we could try to find `get_locale()` in the available saved languages?

**Comment by Spreeuw** [comment]
@alexmigf per-language settings for WPML is a feature of the Professional extesnion (and so is the `wcpdf_order_locale` meta)
