### ISSUE TITLE
[v2.0-b5] Missing line breaks in Shop Address

### ISSUE THREAD

**Issue by thomas-zg** [wpovernight/woocommerce-pdf-invoices-packing-slips#21]
The shop address in the generated PDF is missing the line breaks between the address lines:
<img width="335" alt="bildschirmfoto 2017-06-15 um 21 02 37" src="https://user-images.githubusercontent.com/25877146/27197617-35629c18-520f-11e7-9580-7ae2c89be338.png">

**Comment by Spreeuw** [comment]
closed by 8741517
