### ISSUE TITLE
Invoice numbering starts at 000001

### ISSUE THREAD

**Issue by AdriOosterwijk** [wpovernight/woocommerce-pdf-invoices-packing-slips#23]
Hi, after updating to the 2.0-beta 5 version the invoice numbers are starting over at 000001.
Of course I can set the next number but I think it ould be great if users don't have to think about that.

**Comment by Spreeuw** [comment]
This is normally automated upon upgrading, the plugin checks the version number and if 1.6.5 or older was used before, it migrates all the settings. It sounds like for some reason the version detection on your site did not work properly.
This would also explain the font/template issue you were having in #22.

Have you ever manually changed the version number of the plugin?

**Comment by Spreeuw** [comment]
fixed with beta 7
