### ISSUE TITLE
Dropbox connection lost 

### ISSUE THREAD

**Issue by AdriOosterwijk** [wpovernight/woocommerce-pdf-invoices-packing-slips#24]
After updating to version 2.0 beta 5 and re-downloading the Dropbox, Pro and Templates plugins the connection with the Dropbox App folder is lost. It is telling me that is due to a problem with capitals.

I can solve it by moving the files by hand to the Apps folder on the Dropbox site but I think it would be nice when this does not happens or is automated.

**Comment by Spreeuw** [comment]
I've sent you an email! This doesn't belong here, since it is about a paid extension.
