### ISSUE TITLE
Enhancement: Bulk download of invoices / packaging slips

### ISSUE THREAD

**Issue by Coernel82** [wpovernight/woocommerce-pdf-invoices-packing-slips#250]
Make an option to bulk download invoices for a customizable date range with presets for current year and last year

**Comment by Spreeuw** [comment]
Hi! This is a function we already offer in our [Professional extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-professional/). We have no plans to add this to the free plugin.
