### ISSUE TITLE
add filename document property

### ISSUE THREAD

**Issue by LDAV** [wpovernight/woocommerce-pdf-invoices-packing-slips#26]
First, many thanks for this important upgrade.

Cause of all these changes of 2.0+ version, it could be necessary to prepare two models for the same template. We must have a _custom-template.php_ for who has wcpdf < 1.7 and _custom-template2.php_ for those who have wcpdf >= 2.0
Now all these templates are located using ... `$this->type . ".php"`
If you add a document properties "filename", should be easier to have different templates.
For instance, in /includes/documents/class-wcpdf-invoice.php row 29
```
public function __construct( $order = 0 ) {
		// set properties
		$this->type	= 'invoice';
		$this->filename	= 'invoice.php';
		...
```
and consequently in /includes/documents/abstract-wcpdf-order-document.php row 575:
```
	public function locate_template_file( $file ) {
		if (empty($file)) {
			$file = $this->filename;
		}
		...
```
In this way if I would add a new document called _newdocument_ I can use a different name of template depending of wcpdf version:
```
			if(version_compare( WPO_WCPDF()->version, '1.7', '<' ) ) {
				include_once 'includes/class-wcpdf-integration.php';
			} else {
				include_once 'includes/class-wcpdf-integration2.php';
			}

```
in first case we have:
```
public function __construct( $order = 0 ) {
		// set properties
		$this->type	= 'newdocument';
		$this->filename	= 'newdocument.php';
		...
```
in second case:
```
public function __construct( $order = 0 ) {
		// set properties
		$this->type	= 'newdocument';
		$this->filename	= 'newdocumentV2.php';
		...
```

**Comment by Spreeuw** [comment]
I don't think this would work the way you describe - after all the old versions don't use the document object.

Semantically I think it's much better to keep the old 1.6.5 templates and new 2.0+ templates in separate folders. Then serve up the correct folder/location based on the plugin version. That way you have all templates for one version in a single place and no confusion over which is applicable.

You can use the `wpo_wcpdf_template_file` filter ([here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/8741517911aa2d26d6c03c1c9489b38cc459f2d6/includes/documents/abstract-wcpdf-order-document.php#L587)) if you need to serve files based on a specific rule.

Let me know if I am missing anything or if I misunderstood!

**Comment by LDAV** [comment]
I try to explain better. Maybe I'm wrong, but please follow my thought.
Our plugin adds a new PDF document to orders. We must provide a template for it.
It could be possibile that our plugin will be updated at the new version, but wcPDF remain v1.6.5.
So we have to check if wcPDF is 2.0+ or up to 1.6.5 version, and provide different solutions with different code.
Consequently, we have to provide two versions of template file: the old one, for <= v1.6.5, called _custom.php_, and the second one _custom2.php_ if they have wcPDF updated.
Yes, we use `wpo_wcpdf_template_file` filter to change that, and it's working now.

Something like this:
```
	add_filter( 'wpo_wcpdf_template_file', array( $this, 'wcpdf_template_files'), 20, 3 );
	public function wcpdf_template_files( $file_path, $type, $order ) {
		if($type !== "custom" || strpos($file_path, "custom") === false) return $file_path;

		$file = "custom2.php";

		$path = WPO_WCPDF()->settings->get_template_path( $file );
		$file_path = "{$path}/{$file}";

		$fallback_file_path = CustomClass()->plugin_path . 'templates/pdf/Simple/' . $file;
		if ( !file_exists( $file_path ) && file_exists( $fallback_file_path ) ) {
			$file_path = $fallback_file_path;
		}
		return $file_path;
	}
```
As you can see, we make the same control you do before to call the hook `wpo_wcpdf_template_file`
The solution suggested could make this easier, because it doesn't need to do the same job twice.

**Comment by Spreeuw** [comment]
What I meant is that you will need this filter regardless of whether I changed this or not, because the old version will not change and not use the document object. So you will need to have a mechanism to determine which template file to serve up either way. I would suggest to make two versions of custom.php, each in their own folder:
```
templates/
 1.6.5/custom.php
 2.0/custom.php
```
Then when you do your version checking, you can assign either file/path using the `wpo_wcpdf_template_file` filter.

I checked [your code](https://github.com/LDAV/woocommerce-pdf-italian-add-on/blob/master/includes/class-wcpdf-integration.php#L157-L170) but couldn't find the version switching yet? Seeing a complete example may help to understand the issue.

**Comment by LDAV** [comment]
you are right. Sorry.
Here it is:
https://github.com/LDAV/woocommerce-pdf-italian-add-on/tree/test
