### ISSUE TITLE
Generate invoice number on order creation

### ISSUE THREAD

**Issue by tibs245** [wpovernight/woocommerce-pdf-invoices-packing-slips#265]
Actually the plugin generate invoice number only on PDF creation.

But if we desactivate automatic send invoice by mail. We have not hook for reserve invoice number for order.

I think it's interessing to reserve hook for that or add invoice number creation on order creation. (Maybe both ? )

My side, I have fixed that with that for the moment : 

```php
add_action('woocommerce_payment_complete', 'createInvoiceNumber', 9999, 1);
add_action( 'woocommerce_order_status_pending', 'createInvoiceNumber', 9999, 1);
add_action( 'woocommerce_order_status_failed', 'createInvoiceNumber', 9999, 1);
add_action( 'woocommerce_order_status_on-hold', 'createInvoiceNumber', 9999, 1);

function createInvoiceNumber($order_id) {
    $order = wc_get_order($order_id);
    $invoice = wcpdf_get_invoice( $order );
    $is_new = false === $invoice->exists();

    // check if we have number, and if not generate one
    if( $is_new ) {
        $invoice->init();
        $invoice->save();
    }
}
```

**Comment by Spreeuw** [comment]
I'm not sure what sort of hook you're looking for here, can you elaborate?
Your function can be simplified to:
```php
function createInvoiceNumber($order_id) {
    $invoice = wcpdf_get_invoice( $order, $init = true );
}
```

In other words, `wcpdf_get_invoice( $order, $init = true )` is all you need to create an invoice! The `$init` parameter will only have effect if the invoice doesn't exist yet.
