### ISSUE TITLE
Preview gets stuck when no WC orders

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#266]
by @YordanSoares 

> The first issue I had is that I created a new staging site, and immediately I installed this branch build, but since there was no orders yet, the PDF preview get stuck:

![pdf-invoices-preview-stuck](https://user-images.githubusercontent.com/38109855/148080892-8e6e187c-912e-4f79-ac6d-ac97d32e9712.gif)

> I checked the console and saw this error:

![image](https://user-images.githubusercontent.com/38109855/148080931-d21a764e-c503-4f2d-bb44-3479d92af8c1.png)

> Maybe it's a good idea to show sample order data as default, if there aren't orders yet in a new store. This option could be also added in the top right dropdown, beside **Show last order**, and **Show for an order**, something like **Show sample order**. We could add the sample data, something like:

```
Address:
John Doe
Street 123
33035 Miami

Order Number: 123
Order date: $current_date;

Some test items
```

> However, if the above suppose too much work for this MVP version, we could just add a check while loading the preview and display a message if there are no orders yet, to invite the user to create a test order first.

**Comment by alexmigf** [comment]
Fixed here ca4a3e1

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by dpeyou** [comment]
@alexmigf 

![pdfPreviewNoOrders](https://user-images.githubusercontent.com/74280840/148394089-afd70429-3ff5-4964-a354-0b9b7d5ac37a.png)
