### ISSUE TITLE
Get rid of the 'Show specific invoice number' option, and just leave the 'Search for an order' option

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#267]
by @YordanSoares 

> Although later I found the **Show specific invoice number** option, I first chose **Search for an order**, and I thought that maybe you forgot to add the order number search there:

![image](https://user-images.githubusercontent.com/38109855/148080188-b95f8de7-80ea-48e2-806b-3f6353d71e0f.png)

> I think we could just get rid of the **Show specific invoice number** option, and just leave the **Search for an order** option, adding the order number in the query, what do you think about it?

**Comment by alexmigf** [comment]
We prior discussed to have 2 order search types:

* **Show specific order number**
* **Search for an order:** which tries to find it from: `customer` (email), `customer_id`, `billing_first_name`, `billing_last_name` or `billing_company`

**Comment by alexmigf** [comment]
@dpeyou said:

What about something like:
- Search order number
- Search order info

As it stands **search for an order** it is ambiguous, potentially making it an additional source of anger for an already impatient person because I 100% believe people will enter the order number in that one, only to find zero results.

**Comment by Spreeuw** [comment]
closed by 7477f4d
