### ISSUE TITLE
Preview error messages not being removed

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#271]
by @Terminator-Barbapapa 

> Error messages are not removed, so they keep on stacking. Even if an order was found eventually.

<img width="944" alt="Schermafbeelding 2022-01-05 om 16 20 28" src="https://user-images.githubusercontent.com/19350150/148247118-eb7f57a4-4612-476e-8dcb-151f72d88942.png">

**Comment by alexmigf** [comment]
Fixed here: ca4a3e1f49825fe0187f2168d9bf56d3626b88e6

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by dpeyou** [comment]
I wasn't able to reproduce this error message stacking. :)
