### ISSUE TITLE
Errors message sometimes stack in the search results

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#272]
by @Terminator-Barbapapa 

> Errors message sometimes stack in the search results window. Not quite sure why.

<img width="347" alt="Schermafbeelding 2022-01-05 om 16 37 52" src="https://user-images.githubusercontent.com/19350150/148247405-158d075f-2370-41b2-a3a3-2223fd87b483.png">

**Comment by alexmigf** [comment]
I couldn't replicate this. Can you describe the steps that lead to this issue?

**Comment by Terminator-Barbapapa** [comment]
Unfortunately I have yet to find out why this occurs. It just happend out of the blue. And after that I could sometimes replicate the behaviour by keep typing characters while there was a search going. I'll look into the code to see if I can find why this can happen.

**Comment by Spreeuw** [comment]
Should be fixed by eb1cca45ba5245ffd1c9d60b52f72ac9b9596e82 (and related commits)
