### ISSUE TITLE
Spinner comes sliding in from the left when searching for an order

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#273]
by @Terminator-Barbapapa 

> Spinner comes sliding in from the left when searching for an order. Which looks a bit odd.

**Comment by alexmigf** [comment]
Fixed here: 9cd009bec08e3b62371c0fb24f66e32895e6e648

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by dpeyou** [comment]
![test](https://user-images.githubusercontent.com/74280840/148430066-83007f5a-4c36-4208-b2b4-d9696c52a1d4.gif)

**Comment by alexmigf** [comment]
@dpeyou is the spinner from the "Search for an order" (last option).

**Comment by dpeyou** [comment]
@alexmigf 
![test3](https://user-images.githubusercontent.com/74280840/148817630-8ebcbb5d-1cb3-407c-a16b-1327c7806636.gif)

**Comment by alexmigf** [comment]
@dpeyou seems fine to me.
