### ISSUE TITLE
Clear input button is still visible when switching preview types

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#274]
by @Terminator-Barbapapa 

> Clear input button is still visible when switching from 'Search for an order' to 'Show last order' or 'Show specific order number'.

**Comment by alexmigf** [comment]
Fixed here: 3faf6381335f65f3f937b05049a5188592026782

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by dpeyou** [comment]
@alexmigf I'm not sure what this button is, but I suppose that's good news:
![test2](https://user-images.githubusercontent.com/74280840/148811480-6dfdf38a-241e-4ba8-aaed-8f29dc5c1566.gif)

**Comment by dpeyou** [comment]
@alexmigf here ya go
![test2](https://user-images.githubusercontent.com/74280840/148813624-d4716f90-e096-4045-bab9-3579d47cfe8f.gif)

**Comment by alexmigf** [comment]
@dpeyou seems fine to me :+1:
