### ISSUE TITLE
'Show last order' does not actually load the last order

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#275]
by @Terminator-Barbapapa 

>  'Show last order' does not actually load the last order.

**Comment by alexmigf** [comment]
I couldn't replicate this. It's working fine for me. What others think?

@wpovernight/plugin-devs

**Comment by alexmigf** [comment]
Maybe it was because you had the Invoice document disabled. I have fixed that here: 2ccd5b7cbd5ece284339148ba5f7a5b9cc9e356c

**Comment by dpeyou** [comment]
- Last order total = 0.00
- Invoice generated
- Disable for free order: YES, Preview loads forever
- Disable for free order: NO, Preview loads successfully

**Comment by alexmigf** [comment]
@dpeyou I can't replicate your issue.

**Comment by dpeyou** [comment]
@alexmigf I can no longer replicate this issue either, now it looks like this:
![Screenshot_2022-01-10_09-39-40](https://user-images.githubusercontent.com/74280840/148784161-26a9575a-6b88-4c8f-ad2b-70b3cee50e95.png)

**Comment by alexmigf** [comment]
@dpeyou good to know, looks fine to me.

**Comment by Spreeuw** [comment]
I would change the error to: "Document not available for order #..."

**Comment by alexmigf** [comment]
> I would change the error to: "Document not available for order #..., try selecting a different order"

Having the Document disabled also throws this error, maybe we should also include that in the message?

**Comment by alexmigf** [comment]
Yes, but the "try selecting a different order" might get the client in a loop trying different order when the document is disabled.

**Comment by Spreeuw** [comment]
Yes, that's why I wrote:

> If the invoice is disabled, the preview feature should be disabled entirely IMO.

in other words: NO preview controls at all.

**Comment by alexmigf** [comment]
Ok, I will open a new issue for that.
