### ISSUE TITLE
Preview is low resolution (grainy)

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#276]
by @Terminator-Barbapapa 

> Preview is low resolution (grainy)

**Comment by alexmigf** [comment]
Fixed here: 4542b64689dabc1f8efeccdf8888f372fc993ef8

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by Spreeuw** [comment]
✔️ I'm not experiencing any graininess in Chrome or Firefix on Windows (but admittedly I didn't notice it before either)
