### ISSUE TITLE
Add a max width for the preview

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#278]
by @Terminator-Barbapapa 

> Add a max width for the preview

**Comment by alexmigf** [comment]
Fixed here: 98db34e3386127ca995578781a4e022904c8ebbd

**Comment by alexmigf** [comment]
@Terminator-Barbapapa can you review?

**Comment by Spreeuw** [comment]
@alexmigf what's the reason you picked `cm` as the unit for something that's only displayed on the screen?
@Terminator-Barbapapa what was your original reason for wanting to have a max-width? (since the issue contains no further explanation/context)

**Comment by Terminator-Barbapapa** [comment]
Before the preview would stretch to fit the available space. In full preview mode this means 70% of the container, as the container then has 15% padding on both sides. On a large desktop this would become quite big I think. So that's why I though it might be a good idea to have a max-width.

**Comment by Spreeuw** [comment]
what would you propose? Do you think `cm` is the correct unit here (since you are referring to physical size)

**Comment by Spreeuw** [comment]
I think this broke the full screen preview mode somehow (it's also possible this was caused by the 'sticky' implementation #303 ?), it looks like the preview no longer moves, and in fact it even becomes smaller instead of larger!

**Comment by alexmigf** [comment]
Indeed, it was because of the sticky implementation. I have fixed the issue here 4986afc747bd485b9db024cbc6009c365dbf0dae but I couldn't fix it in full preview, so I have disabled it when viewing in `full`, is this an issue?

**Comment by Spreeuw** [comment]
We definitely don't need sticky for full screen (since the document itself is the only thing that's being scrolled), but I wonder if the way you're 'unsticking' it now (with CSS) is the best way - the preview states are already being controlled by JS so I would just use the native `hcSticky` methods like `.destroy()` or `.refresh()`.

**Comment by alexmigf** [comment]
@Spreeuw fixed here: f2d4e407d64f826b10c2feb4282ec4f2ff2e4df8

**Comment by Spreeuw** [comment]
:100:

**Comment by Spreeuw** [comment]
@alexmigf @Terminator-Barbapapa this can be closed I think?

**Comment by alexmigf** [comment]
Currently it has `900px` don't know if should be replaced with `vw` units, what you think @Terminator-Barbapapa ?

**Comment by Terminator-Barbapapa** [comment]
I think we need to set a static width to prevent the preview from becoming huge on larger screens. But I think we can set a different `max-width` for larger screen sizes.

**Comment by alexmigf** [comment]
@Terminator-Barbapapa do you still need to do anything here?

**Comment by Terminator-Barbapapa** [comment]
We haven't set a max width for larger screens yet. Who has the largest monitor here?

**Comment by alexmigf** [comment]
32" here

**Comment by Terminator-Barbapapa** [comment]
@alexmigf How does sidebar and full screen preview look for you? Is the preview too small?

**Comment by alexmigf** [comment]
![Captura de ecrã de 2022-02-22 08-23-53](https://user-images.githubusercontent.com/533273/155091805-5d5ccd9f-47bb-4901-ac27-37d6e56d9582.png)
![Captura de ecrã de 2022-02-22 08-23-35](https://user-images.githubusercontent.com/533273/155091810-673b6281-d427-45f0-8f61-4f0bff16b26a.png)

**Comment by Terminator-Barbapapa** [comment]
Looks okay to me. What do you think @Spreeuw? We could enlarge it a bit more. Maybe `1000px`?

**Comment by Spreeuw** [comment]
Honestly I think it's fine, making it bigger also means more is cut off the bottom.

**Comment by alexmigf** [comment]
I think it's fine too.

**Comment by Terminator-Barbapapa** [comment]
Agreed. Looking at it today I think `900px` is already quite large for medium desktops. So we could also set the default to `max-width: 800px` and for large desktops go with `max-width: 900px`.

**Comment by Spreeuw** [comment]
@Terminator-Barbapapa is your last remark still a 'todo'? I think we're done reviewing this, so as soon as that's implemented we can close this issue

**Comment by Terminator-Barbapapa** [comment]
Tweaked the max width in commit https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/91022b1570ad7ac7b2071dcd519c183dfdd12918
