### ISSUE TITLE
Preview is not working with external invoice numbers

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#280]
by @Terminator-Barbapapa 

> Preview is not working with external invoice numbers

**Comment by alexmigf** [comment]
@Terminator-Barbapapa I believe the Preview is working, just not displaying the third party number, I'm correct?

**Comment by Terminator-Barbapapa** [comment]
That's right. The preview is showing but not with the correct number.

**Comment by Spreeuw** [comment]
@Terminator-Barbapapa what would 'the correct number' be? where do the external invoice numbers come from?

**Comment by alexmigf** [comment]
@Spreeuw I think he is referring the use of this hook `wpo_wcpdf_external_invoice_number`

**Comment by Terminator-Barbapapa** [comment]
Correct. If I create a custom invoice number by using `wpo_wcpdf_external_invoice_number` this will not show up on the preview.

**Comment by Spreeuw** [comment]
to be absolutely clear: only for orders that don't have an invoice yet, right?

This action hook is only triggered when the invoice is created:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/81effce2cc20319d0055a98b8d4cd0e7f8462917/includes/documents/class-wcpdf-invoice.php#L83-L89

Which is something we definitely do NOT want to do in the preview 😉

**Comment by Terminator-Barbapapa** [comment]
No, also for orders that already have an invoice. 

Invoice for my last order:
<img width="245" alt="Schermafbeelding 2022-01-07 om 15 20 03" src="https://user-images.githubusercontent.com/19350150/148557133-7aad9202-841e-450d-90f1-428aad817f8e.png">

Preview for my last order:
<img width="257" alt="Schermafbeelding 2022-01-07 om 15 21 27" src="https://user-images.githubusercontent.com/19350150/148557225-f119deaf-07d5-4da1-b000-fbe2e31a8436.png">

**Comment by Spreeuw** [comment]
that's a bug then, unless you have filters besides `wpo_wcpdf_external_invoice_number`
What's the number you see in the order backend?

**Comment by Terminator-Barbapapa** [comment]
It shows the correct number in the order backend:
<img width="307" alt="Schermafbeelding 2022-01-07 om 15 29 53" src="https://user-images.githubusercontent.com/19350150/148558374-b5ac4673-d837-4eaf-a8cd-0f42d4aca205.png">

I'm only using `wpo_wcpdf_external_invoice_number_enabled` and `wpo_wcpdf_external_invoice_number`.

**Comment by Spreeuw** [comment]
@alexmigf can you look into this? If an order already has an invoice number, it should show that, not a new number.

**Comment by alexmigf** [comment]
@Spreeuw sure

**Comment by alexmigf** [comment]
Fixed here b92241a885f8318dfcc1714f18e6a9d3f45e6312

Can you test too @Terminator-Barbapapa ?

**Comment by Terminator-Barbapapa** [comment]
Displaying the correct invoice number for existing documents now. :)
