### ISSUE TITLE
Styling improvements for Preview settings

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#281]
by @Spreeuw 

- [x] Don't use `font-weight: 300`. While I like this from a stylistic point of view, in isolation, it doesn't integrate with the rest of WordPress / WooCommerce settings. We should stick to the default weights for headers & text. For The tabs, that means: `font-weight: 600` (or better: not defining it so that the core WP styles are used). Also better for readability/accessibility. 
![wcpdf-preview-font-weight](https://user-images.githubusercontent.com/3217773/148286774-e009c2db-ed25-4152-a9a8-bc24b367cda7.png)
![wcpdf-preview-font-weight-normal](https://user-images.githubusercontent.com/3217773/148286780-fcf670e7-5584-48c7-8593-afa79b8306fe.png)
- [x] Increase contrast / change colors for the attachment settings hint. The pink should match the purple you used elsewhere too.
![wcpdf-preview-attachment-hint](https://user-images.githubusercontent.com/3217773/148287088-965d0b44-9562-43b2-97dd-26aec2c9eeec.png)
- [x] Don't stack settings in wide view, this is only necessary on mobile or sidebar view. We could add a limit to the width of the settings _description_ for readability (full width is too much), but the 'official' WP layout works better in full width (more readable, more efficient space usage).
![wcpdf-full-width-settings-before](https://user-images.githubusercontent.com/3217773/148287679-059e3153-8cf5-4e28-8f49-7426a667894c.png)
![wcpdf-full-width-settings-after](https://user-images.githubusercontent.com/3217773/148287685-01dd7cdd-2324-41f0-b100-c3114ca3b2e6.png)

**Comment by Spreeuw** [comment]
Looks good to me!

**Comment by dpeyou** [comment]
@alexmigf 
![Screenshot_2022-02-14_08-58-08](https://user-images.githubusercontent.com/74280840/153878623-02a7c25a-e115-4a53-9a80-bced7f75ad70.png)

**Comment by dpeyou** [comment]
![Screenshot_2022-02-14_08-58-08](https://user-images.githubusercontent.com/74280840/153882123-42178b23-aac0-4c3b-87fa-c26054db01f6.png)
![Screenshot_2022-02-14_09-24-30](https://user-images.githubusercontent.com/74280840/153882256-25790694-4e5b-4c9f-b11c-54b9ccf5788f.png)

**Comment by alexmigf** [comment]
@dpeyou I can't replicate that. Can you clear the browser cache?

**Comment by Spreeuw** [comment]
@alexmigf @dpeyou I can't replicate the issue with the extra field widths either, but the SFTP form is messy for me too:
![sftp-settings-layout](https://user-images.githubusercontent.com/3217773/154225032-58f50797-3281-4711-8191-af7770887794.png)

**Comment by Spreeuw** [comment]
I've pushed a fix for the FTP style issue to Professional

**Comment by Terminator-Barbapapa** [comment]
I also see the document selector in the 'Documents' tab has some issues. I will provide a fix.

**Comment by alexmigf** [comment]
I'm seeing this:

![Captura de ecrã de 2022-02-21 13-53-07](https://user-images.githubusercontent.com/533273/154976445-4a7179ea-f461-4dd9-b1af-c6c59c17d86c.png)

**Comment by Spreeuw** [comment]
@alexmigf I've made a few tweaks in the Professional extension styles. Honestly I think it's fine for now, we can always improve later too
