### ISSUE TITLE
Integrate Preview with the Customizer

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#282]
by @Spreeuw 

> As discussed previously, and implemented in the mockups too, this should be in the form of a full width settings / full width preview toggle.

**Comment by Terminator-Barbapapa** [comment]
This is already implemented, but it would eventually require a small change in the Premium Templates plugin to show up. Or for now you can activate it with this filter:

```
add_filter( 'wpo_wcpdf_settings_tabs', 'wpo_wcpdf_settings_tabs', 20, 1 );
function wpo_wcpdf_settings_tabs( $settings_tabs ) {
	foreach ( $settings_tabs as $tab_id => &$tab_data ) {
		if ( $tab_id == 'editor' ) {
			$tab_data = array(
				'tab_title' => __( 'Customizer', 'wpo_wcpdf_templates' ),
				'preview_states' => 2,
			);
		}
	}
	return $settings_tabs;
}
```

If the number of preview states are not declared for a tab it defaults to one preview state which is means you can only view the settings.

- One preview state: Only full width settings
- Two preview states: Either full width settings or full width preview
- Three preview states: Either full with settings, sidebar view (settings and preview together) or full width preview

**Comment by Spreeuw** [comment]
> This is already implemented, but it would eventually require a small change in the Premium Templates plugin to show up.

Please create an issue in Premium Templates and implement there. That way we can work with the actual configuration rather than having to add a code snippet!

**Comment by Terminator-Barbapapa** [comment]
Will do. I think the 'Pro' tab is the only other tab that needs a preview. Do we want to give it two or three preview states?

**Comment by Spreeuw** [comment]
I'm not sure if all the tabular data we have on that tab fits the sidebar. If you can make that fit nicely without making things super tall, I guess 3 states is fine.

**Comment by Spreeuw** [comment]
Latest `master` of the Premium Templates adds the preview to the Customizer. Also: `tab_title` is now just `title`.
