### ISSUE TITLE
Some setting inputs are being cut

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#283]
Shop name is being cut on lower resolution:

![Captura de ecrã de 2022-01-06 08-43-52](https://user-images.githubusercontent.com/533273/148354996-227d9025-b347-4ab2-8582-b67aa71732a3.png)

This also:

![Captura de ecrã de 2022-01-06 10-17-35](https://user-images.githubusercontent.com/533273/148367597-720b8aa9-7dae-4ec7-a96f-d1c5fc4e2fd7.png)

**Comment by alexmigf** [comment]
@Terminator-Barbapapa @Spreeuw can you review this commit? 12ac26bd77fda5a65b618dd6a4b3922966c14f29

**Comment by alexmigf** [comment]
I end up fixing this with CSS only here: 710a6fdc97bc2740aba3919139dd8f5c660957f3

**Comment by Spreeuw** [comment]
@alexmigf it looks like you forgot to revert 12ac26b:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/c5064610d8c190bf81792fad51cd50dc0dc84ad1/includes/class-wcpdf-settings-callbacks.php#L84

(FYI: this should normally be handled in the `normalize_settings_args` and if you introduce a new parameter like this it should be added to all callbacks - but that's no longer relevant)

**Comment by alexmigf** [comment]
Done here: a7bc6831a9a698755b2adbb694b300fd704c05c2

**Comment by dpeyou** [comment]
@alexmigf  these, along with the 3 textboxes for the Modern template r being cut-off
![Screenshot_2022-01-10_13-03-41](https://user-images.githubusercontent.com/74280840/148816619-ec86b916-361f-4b8a-9f6f-2aea99a2562d.png)

**Comment by alexmigf** [comment]
@dpeyou can you test again please?

**Comment by dpeyou** [comment]
@alexmigf good to go
![Screenshot_2022-01-17_09-21-42](https://user-images.githubusercontent.com/74280840/149787051-61f88e7d-6f3d-4bcf-8681-661f6435d7dd.png)
