### ISSUE TITLE
Disable Preview controls if document is disabled

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#284]
If the document used for the Preview is disabled we should disable also the Preview controls.

**Comment by alexmigf** [comment]
Maybe we should have a global setting for the document used for the Preview here? https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/268

That would help in this issue.

**Comment by dpeyou** [comment]
@alexmigf I forgot to mention that this error is also thrown if the status of the last order is disabled
![Screenshot_2022-01-10_09-39-40](https://user-images.githubusercontent.com/74280840/148804491-279e113b-6762-4618-9e76-4d0ff0f25182.png)
Would we also want to disable the preview in this case?

**Comment by alexmigf** [comment]
@dpeyou I think that's fixed with the last commits, did you pulled the branch?

**Comment by dpeyou** [comment]
@alexmigf now it looks like this for the above conditions I stated:
![Screenshot_2022-01-17_09-25-56](https://user-images.githubusercontent.com/74280840/149787612-3495e492-556a-465e-aad0-aa1a2589af28.png)

**Comment by alexmigf** [comment]
Not sure I understand. For reference: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/275#issuecomment-1008984608

**Comment by dpeyou** [comment]
@alexmigf sorry, in smy previous comment I should have just said that it is good to go.

however, see https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/270#issuecomment-1014706425
