### ISSUE TITLE
Race condition for yearly reset

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#286]
A user reported duplicate invoice numbers being generated for the first batch of invoices of the year in the forums ([here](https://wordpress.org/support/topic/duplicate-invoice-numbers-mixed-customer-data/#post-15237175)).

This is a race condition specific to the yearly reset. Any regular bulk/parallel request of invoices is race-condition proof (due to the invoice numbers being generated by mysql autoincrement), but the reset is a non-continuous process.

A possible solution to this would be to queue a cron task at the very first second of the new year (time zone-aware!), or alternatively to pre-retire the old year table in favor of the new year table before the new year starts.
That second method is probably more reliable, but it also introduces a potential issue with hardened database setups that don't allow creating new tables (which is the reason why we ended up moving away from that approach in the early development of #164 (originally #153), because it could mean that the last 'old year' invoices couldn't be created anymore.

**Comment by alexmigf** [comment]
> A possible solution to this would be to queue a cron task at the very first second of the new year (time zone-aware!)

Using AS it will use the WP timezone I think no?

**Comment by Spreeuw** [comment]
> Using AS it will use the WP timezone I think no?

Both WP_Cron ([`wp_schedule_single_event()`](https://developer.wordpress.org/reference/functions/wp_schedule_single_event/)) and AS ([`as_schedule_single_action()`](https://actionscheduler.org/api/)) require a timestamp for the action. But that's not a problem in itself: If you convert a date to timestamp and you pass the timezone from the WP settings, or if you use `wc_string_to_datetime()`  (WC3.0+), the timestamp will reflect the localized time.
