### ISSUE TITLE
[v2.0b7] Footer gets not applied when turning off legacy mode

### ISSUE THREAD

**Issue by thomas-zg** [wpovernight/woocommerce-pdf-invoices-packing-slips#29]
I'm using the page numbering like: Seite {{PAGE_NUM}} von {{PAGE_COUNT}}
This is stored in the footer setting and gets not applied when turning off the legacy mode.

**Comment by Spreeuw** [comment]
Works for me in both. Can you share the footer part of your template?

**Comment by thomas-zg** [comment]
Seite {{PAGE_NUM}} von {{PAGE_COUNT}}

**Comment by thomas-zg** [comment]
Just figured out that the footer will be shown when [legacy mode=off] and [enable debug output=on]

**Comment by thomas-zg** [comment]
Made a clean installation and the footer will be shown. I'll have a deeper look to my production copy later today.

**Comment by thomas-zg** [comment]
It is related to some customizations in css, I have to reenable them step by step to figure out which one causes the issue. Will have a deeper look later on.
