### ISSUE TITLE
Change default datetime value for Number Store tables

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#292]
We use `0000-00-00 00:00:00` for the `datetime` default value, which is an invalid value in MySQL8.0.
We should change this and also migrate existing number store tables.

Possible default values:
*  `2014-01-17 12:38:28` - release date of version `1.0.0` of the plugin (could be a bit confusing)
* `1000-01-01 00:00:00` - lowest allowed value
* `1970-01-01 00:00:00` - unix epoch start date

Database migration is needed for this change.

**Comment by alexmigf** [comment]
@Spreeuw have you decided for which one to go?

**Comment by Spreeuw** [comment]
let's use the lowest allowed = `1000-01-01 00:00:00`
