### ISSUE TITLE
Include /dompdf folder during temporary files cleanup

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#295]
Currently, both the [automatic cleanup procedure](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/eefdc6136e465f037cd9e543f6768d04c3014506/includes/class-wcpdf-main.php#L45) as well as the [manual cleanup action](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/eefdc6136e465f037cd9e543f6768d04c3014506/includes/class-wcpdf-settings-debug.php#L100-L138) for the temporary files only clean the PDF files from the `/attachments` folder.

One of our users reported that their `/dompdf` folder was growing quite big, and it turned out that this was because of custom uploaded images that dompdf downloads there to include them in the PDF.

The `/dompdf` folder should be included in both these cleanup processes too (and perhaps this is also a good moment to move them to a central method?)

**Comment by alexmigf** [comment]
@Spreeuw what do you mean by a central method? A dedicated class for storage?
