### ISSUE TITLE
Add filter to control item meta output

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#300]
Item meta is currently printed with the default parameters except for `echo` (because we process it as a string):
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/bd157de31373641b3558128dfae40cbe67c63728/includes/documents/abstract-wcpdf-order-document-methods.php#L625-L627

Some people prefer a different output, usually printing the items on a single line instead of as a list (`ul>li`). The only way to currently do that is to change the list elements to `inline-block` with CSS, for example:
```css
.wc-item-meta li {
	display: inline-block;
}
```
Adding a separator (using `::before` and `content`) is also possible this way although it comes with it's own challenges.

This is sub-optimal because it still includes several elements that may need to be overriden to make it an actual, workable flat list.
We could add a new option for this by applying a filter (`wpo_wcpdf_display_item_meta_args`?) to the `wc_display_item_meta()` args.

This would allow the user to override any of the defaults (using their own separator and skipping the whole ul>li reformatting):
```php
array(
	'before'       => '<ul class="wc-item-meta"><li>',
	'after'        => '</li></ul>',
	'separator'    => '</li><li>',
	'echo'         => true,
	'autop'        => false,
	'label_before' => '<strong class="wc-item-meta-label">',
	'label_after'  => ':</strong> ',
)
```

**Comment by dwalkerpriv** [comment]
i've add this to my functions.php. i left the `before`, `after` and `separator` blank, to see what happens in the pdf.
```

// ADD FILTER TO CONTROL ITEM META OUTPUT

add_filter('wc_display_item_meta', 'wpo_wcpdf_display_item_meta_args', 10, 2);
function wpo_wcpdf_display_item_meta_args( $args ) {

    // Set item meta
        $args = array(
            'before'       => '',
            'after'        => '',
            'separator'    => '',
            'echo'         => true,
            'autop'        => false,
            'label_before' => '<strong class="wc-item-meta-label">',
            'label_after'  => ':</strong> ',
        );

    return $args;
}
```
I'm not seeing much changes/errors in the invoices. What's missing?
![Screenshot 2022-01-25 052949](https://user-images.githubusercontent.com/62675729/150960275-1d9ffca9-5649-4538-8d92-d23132a19a74.png)

**Comment by Spreeuw** [comment]
@dwalkerpriv that's hard to say without seeing your filter implementation. Can you open a PR with those changes so I can review it? Also note that you have set `2` arguments but your function only accepts 1.
