### ISSUE TITLE
make preview sticky

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#303]
When the settings page is long and you scroll down, the preview disappears at the top - making it much harder to see the effect of changes you make. If the preview is made sticky, you no longer have to scroll up to see the effects

**Comment by alexmigf** [comment]
I think we might have a problem here if we try to use CSS to set the Preview as sticky. The ancestors can't have the instruction `overflow:hidden`, which already has [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/a6e1f055c9b2dc66bb1410f157f906ba587bd92e/assets/css/settings-styles.css#L225) to hide the arrow when we close the Preview to the right:

![Captura de ecrã de 2022-01-27 10-29-27](https://user-images.githubusercontent.com/533273/151341119-d6e20e9f-3f3b-4289-8ec6-4a98de98102b.png)

The alternative seems to use JS. Your thoughts @Spreeuw ?

**Comment by Spreeuw** [comment]
I don't mind using JS. I didn't even know there was a CSS-only solution to this, but maybe we don't mean the same thing by 'sticky'? What I meant was that the preview will start moving down as soon as the top reaches the top of the window (keeping in mind that the top part is variably sized, based on whether there are admin notices).

**Comment by alexmigf** [comment]
I understood, I think we are referring the same thing, the Preview will follow the scrolling down so you always have it visible.

**Comment by Spreeuw** [comment]
Looks good to me! @Terminator-Barbapapa can you review too?

**Comment by Spreeuw** [comment]
@alexmigf I noticed that the preview disappears when I've reached the bottom of the page, and then when I scroll up again, it becomes flaky (sometimes it disappears and then when I scroll further it appears again, disappears, etc).

**Comment by alexmigf** [comment]
@Spreeuw fixed here: 5d4ab81b89896534b1633c2ac3ed2ad56da42f46

**Comment by Spreeuw** [comment]
The result is now that I can no longer scroll to the bottom of the preview, which was better before.

**Comment by Spreeuw** [comment]
Another thing that broke with that last commit is that after I go to full screen and then go back to sidebar, the sticky preview is not reattached.

**Comment by alexmigf** [comment]
I'm not seeing that. In which page?

**Comment by Spreeuw** [comment]
> I'm not seeing that. In which page?


The sticky becoming detached? I get that on the General as well as on the Documents page. It's because in https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/5d4ab81b89896534b1633c2ac3ed2ad56da42f46 you detach when moving left regardless of what state you were in. So, when I move to full screen settings, then back to sidebar (left), it's no longer attached.

**Comment by alexmigf** [comment]
> The result is now that I can no longer scroll to the bottom of the preview, which was better before.

I was referring to this, sorry!

**Comment by Spreeuw** [comment]
i get that on all pages. Before the change, when I reached the bottom of the settings page, the preview would scroll to the bottom of the page too. Now it's cut off at the bottom of the window, even after I've reached the end of the page, it's still in the same position:
![preview-bottom-of-page](https://user-images.githubusercontent.com/3217773/152509243-d9d6da64-74e6-4fa5-abd2-c601fec7e97d.png)

**Comment by alexmigf** [comment]
@Spreeuw could you try now with the last commits?

**Comment by Spreeuw** [comment]
No difference for the scrolling issue, detachment issue seems to be solved.
Code wise, you should merge the ternary with the if-statement:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/f8003d2de3ec5251fbd41641e2fea04d3e3cd588/assets/js/admin-script.js#L62-L64
same here:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/f8003d2de3ec5251fbd41641e2fea04d3e3cd588/assets/js/admin-script.js#L85-L87

Although I wonder if there's ever an action when `slide-right` is triggered when the preview is closed? Because that button no longer exists then?

**Comment by alexmigf** [comment]
Fixed here: 014459107fccd11f1004f8c5f206517c58408e70

**Comment by alexmigf** [comment]
The scroll issue (preview disappear when reach bottom) has to do with the `#wpo-wcpdf-preview-wrapper` size. A possible solution could be adding extra padding to the `sidebar` bottom for example. What you think?

**Comment by Terminator-Barbapapa** [comment]
I wonder if it would be better to shrink the preview to about 95% of the view height when in sticky mode. That way you will have a full overview of the document. Right now you will have to scroll all the way to the bottom to see the footer (which isn't yet working for me though).

Also shouldn't the slider arrows and perhaps the document switcher and order search move along with the preview?

**Comment by Spreeuw** [comment]
> I wonder if it would be better to shrink the preview to about 95% of the view height when in sticky mode. That way you will have a full overview of the document

that's an n=1 argument because I would need a lot more shrinkage on my laptop 😆 
but yeah, shrink to fit would be nice indeed

> Also shouldn't the slider arrows and perhaps the document switcher and order search move along with the preview?

They used to do that in the first iteration, @alexmigf did you change this for a reason?

**Comment by Spreeuw** [comment]
Or should the settings and preview scroll independently? Or is that a UX nightmare?

**Comment by alexmigf** [comment]
> They used to do that in the first iteration, @alexmigf did you change this for a reason?

The left and right arrows move, the document switcher and search wasn't fixed before?

**Comment by Terminator-Barbapapa** [comment]
I've made a small mock-up that uses CSS sticky in combination with flexbox. The only JS here is that the preview resizes when the container hits the top of the viewport. Maybe the preview in sidebar mode should always be the full height of the viewport (and then sticky when scrolling.

https://user-images.githubusercontent.com/19350150/152530838-bc510b4b-85d1-4869-bf24-c36e65365cda.mov

**Comment by Spreeuw** [comment]
@Terminator-Barbapapa that looks great! @alexmigf what do you think?

**Comment by alexmigf** [comment]
Love the idea!

**Comment by Terminator-Barbapapa** [comment]
If we make the preview sticky I think we'll have adjust its height to the viewport when in sidebar mode though. So in sidebar mode you will always see the full document. It is a bit weird that you have to scroll down in the settings to see the bottom part of the preview.

**Comment by Spreeuw** [comment]
Go for it @Terminator-Barbapapa

**Comment by Spreeuw** [comment]
I see this is still in progress, but I wanted to mention it in case you hadn't noticed, the document selector dropdown is now hidden behind the preview
![document-dropdown-index](https://user-images.githubusercontent.com/3217773/153406122-e04fbb3d-8cd1-4ff3-8793-2bbc34d81db7.png)

**Comment by Spreeuw** [comment]
>  So if you've scrolled down far enough the preview is suddenly gone.

Isn't that because you keep the settings visible (docked to the side) instead of hiding them? Otherwise the page would just become smaller and the scroll position adjusted automatically?

**Comment by Terminator-Barbapapa** [comment]
I was thinking exactly the same. :)
Committing right now.

**Comment by Spreeuw** [comment]
What's the `170vh` value based on?

**Comment by Terminator-Barbapapa** [comment]
When the preview is sticky it has `max-height: 85vh`. So it will always fit in the viewport when scrolling down. When the preview goes into full preview mode it gets `max-height: 170vh'. So it can expand to 1.7 times the viewport height (with `max-width: 900px'). 

The sidebar and gutter never have to be larger than `170vh` because the preview can never get any higher than that.

**Comment by Terminator-Barbapapa** [comment]
Improved the preview's resize CSS transitions: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/b9d4dde6229132423f0c77e996af77b55b0be8b5

With the help from the [new](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/318) `data-from-preview-state` attribute.

**Comment by Terminator-Barbapapa** [comment]
I think with commit https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/2fc282137a48d1ed312b66b45c37bea12f4e7aa2 this is now done. Closing for now.
