### ISSUE TITLE
[Not an issue] ETA on v2.0?

### ISSUE THREAD

**Issue by Ver3** [wpovernight/woocommerce-pdf-invoices-packing-slips#31]
We launch a new site 10th of Juli. Will it be ready before that? Just curious.

**Comment by Spreeuw** [comment]
We're hoping to release next week! Have you found any issues in 2.0?

**Comment by Ver3** [comment]
Awesome. Not tested yet, will try it monday at work.

**Comment by Spreeuw** [comment]
Just a small update to let you know we've decided to give third party developers a bit more time to update their integrations, so release is now planned for next week. I would say it's safe to use RC1 though!

**Comment by Ver3** [comment]
@Spreeuw Dankjewel voor de update!

**Comment by Spreeuw** [comment]
2.0 is now officially out!
