### ISSUE TITLE
Connect preview slider border to notifications

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#311]
Right now there is a gap between the notifications added via the `wpo_wcpdf_before_settings_page` hook and the border of the preview slider. 

<img width="992" alt="Schermafbeelding 2022-02-04 om 16 24 28" src="https://user-images.githubusercontent.com/19350150/152555268-991d86c5-f6e9-4648-a882-6253a7509338.png">

**Comment by Spreeuw** [comment]
@Terminator-Barbapapa didn't you already fix this before?

**Comment by Terminator-Barbapapa** [comment]
Only quickly checked a possible solution in the Chrome dev tools. Didn't commit yet.

**Comment by alexmigf** [comment]
Seems good to me:

![Captura de ecrã de 2022-02-14 08-52-24](https://user-images.githubusercontent.com/533273/153831002-1b178df1-e058-41cb-8b52-e4978bc86a83.png)
