### ISSUE TITLE
Fix styling order select dropdown

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#316]
<img width="383" alt="Schermafbeelding 2022-02-09 om 15 02 52" src="https://user-images.githubusercontent.com/19350150/153216691-6dd4bf61-e294-49e3-84ef-a242071b0b6b.png">

**Comment by alexmigf** [comment]
@Terminator-Barbapapa I also see this:

![Captura de ecrã de 2022-02-14 08-46-42](https://user-images.githubusercontent.com/533273/153830326-1ad50524-855d-4a43-922f-18c8d14f707a.png)
![Captura de ecrã de 2022-02-14 08-46-37](https://user-images.githubusercontent.com/533273/153830332-4f43696b-e5c5-4a8d-9851-d14d2f3ac5cb.png)

**Comment by Terminator-Barbapapa** [comment]
@alexmigf On larger screen sizes right? I'll create a separate issue for that.
