### ISSUE TITLE
PHP notices on activation

### ISSUE THREAD

**Issue by DavidAnderson684** [wpovernight/woocommerce-pdf-invoices-packing-slips#32]
On the test site I am trying this out on, I had a previous version installed, but it was inactive. I received these PHP notices upon activating.

`PHP Notice:  Undefined index: email_pdf in wp-content/plugins/woocommerce-pdf-invoices-packing-slips/woocommerce-pdf-invoices-packingslips.php on line 391
PHP Stack trace:
PHP   1. {main}() wp-admin/plugins.php:0
PHP   2. require_once() wp-admin/plugins.php:10
PHP   3. require_once() wp-admin/admin.php:31
PHP   4. require_once() wp-load.php:37
PHP   5. require_once() wp-config.php:117
PHP   6. do_action() wp-settings.php:469
PHP   7. WP_Hook->do_action() wp-includes/plugin.php:453
PHP   8. WP_Hook->apply_filters() wp-includes/class-wp-hook.php:323
PHP   9. WPO_WCPDF->do_install() wp-includes/class-wp-hook.php:298
PHP  10. WPO_WCPDF->upgrade() wp-content/plugins/woocommerce-pdf-invoices-packing-slips/woocommerce-pdf-invoices-packingslips.php:272

PHP Warning:  Invalid argument supplied for foreach() in wp-content/plugins/woocommerce-pdf-invoices-packing-slips/woocommerce-pdf-invoices-packingslips.php on line 391
PHP Stack trace:
PHP   1. {main}() wp-admin/plugins.php:0
PHP   2. require_once() wp-admin/plugins.php:10
PHP   3. require_once() wp-admin/admin.php:31
PHP   4. require_once() wp-load.php:37
PHP   5. require_once() wp-config.php:117
PHP   6. do_action() wp-settings.php:469
PHP   7. WP_Hook->do_action() wp-includes/plugin.php:453
PHP   8. WP_Hook->apply_filters() wp-includes/class-wp-hook.php:323
PHP   9. WPO_WCPDF->do_install() wp-includes/class-wp-hook.php:298
PHP  10. WPO_WCPDF->upgrade() wp-content/plugins/woocommerce-pdf-invoices-packing-slips/woocommerce-pdf-invoices-packingslips.php:272

**Comment by DavidAnderson684** [comment]
By the way, I only knew of the coming 2.0 because of casual browsing. Any chance of a direct notification next time?

**Comment by Spreeuw** [comment]
Apologies for not notifying you yet. I have sent out a mailing but completely forgot to include you...
