### ISSUE TITLE
Allow overriding order search parameters

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#324]
It should probably reset the `order_id`, search for the last refund order and also limit the order search to refund orders.

**Comment by Spreeuw** [comment]
@alexmigf changes in free should be limited to adding controls to override the processes, credit note specific stuff should be handled in Professional (open a separate issue there)

**Comment by alexmigf** [comment]
@Spreeuw can you review this and close if good enough?

**Comment by Spreeuw** [comment]
I was thinking you might need frontend (JS) control too, but maybe it can work without that too (and if it can - all the better!)
