### ISSUE TITLE
Unescaped translation strings

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#326]
Several new strings for the preview are not escaped, like this one:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/bc1a371781ddfb16a9c11bd53f38790488888ca8/includes/class-wcpdf-settings.php#L170

(there are several others)

**Comment by alexmigf** [comment]
@Spreeuw can you review [this](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/d3b3f6f72758d912b667a2acc96ea16a4f4d8934) commit?

**Comment by Spreeuw** [comment]
LGTM
