### ISSUE TITLE
Fatal error due to backwards incompatibility

### ISSUE THREAD

**Issue by DavidAnderson684** [wpovernight/woocommerce-pdf-invoices-packing-slips#33]
Hi Ewout,

I wasn't sure from your post about the 2.0 beta where it's intended to be API backwards-compatible, or not. The current version of the Automatic Order Print extension, if active, will cause a PHP fatal error every time an invoice is generated, in any context (i.e. whether automatic printing is happening, or not). If you can add back the property to the class, it'll avoid a lot of trouble from my/our users (some will come to me if they can read PHP logs; others to you because they won't realise how to find out the source). Of course, I will put out a release - but, being a Premium plugin, a lot of people won't update (because they never entered their licence, etc. - and in the past we had a release with a non-functional updater too).

Ironically, the fatal is caused by trying to detect the version of your plugin in order to apply version-specific code! The lines causing the fatal are these:

```
global $wpo_wcpdf;
$version = $wpo_wcpdf::$version;
```

Here's the backtrace:

```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: WPO\WC\PDF_Invoices\Legacy\WPO_WCPDF_Legacy::$version in wp-content/plugins/woocommerce-printorders/print-orders.php:221
Stack trace:
#0 wp-includes/class-wp-hook.php(300): WooCommerce_Ext_PrintOrders->wpo_wcpdf_billing_address('David Anderson<...')
#1 wp-includes/plugin.php(203): WP_Hook->apply_filters('David Anderson<...', Array)
#2 wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document-methods.php(110): apply_filters('wpo_wcpdf_billi...', 'David Anderson<...', Object(WPO\WC\PDF_Invoices\Documents\Invoice))
#3 wp-content/plugins/woocommerce-pdf-invoices-packin in wp-content/plugins/woocommerce-printorders/print-orders.php on line 221
```

**Comment by Spreeuw** [comment]
Thanks david - that's a simple fix :)
Backwards compatibility takes care of handling everything that was going through $wpo_wcpdf, so this should definitely be included indeed.
