### ISSUE TITLE
Improve or remove i18n for log strings

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#333]
The following lines  i18n need to be improved (adding comments for translators and numbered placeholders) or removed (as we did in https://github.com/wpovernight/wc-reminder-emails/pull/20, base on @Spreeuw comments [here](https://github.com/wpovernight/wc-reminder-emails/pull/20#discussion_r584980992)):

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/ee1e1424e2c9053bb417892b6524bd394d400f43/includes/documents/abstract-wcpdf-order-document.php#L1078

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/ee1e1424e2c9053bb417892b6524bd394d400f43/includes/documents/abstract-wcpdf-order-document.php#L1089

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/ee1e1424e2c9053bb417892b6524bd394d400f43/includes/documents/abstract-wcpdf-order-document.php#L1135

**Comment by Spreeuw** [comment]
Let's remove it!
