### ISSUE TITLE
Prevent potential Invoice Number & Date display issues for Preview in template files

### ISSUE THREAD

**Issue by dpeyou** [wpovernight/woocommerce-pdf-invoices-packing-slips#359]
This issue can be resolved in the template by replacing `isset()` with `! empty()`, 
Related to this: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/358

**Comment by Spreeuw** [comment]
Originally reported here: https://wordpress.org/support/topic/invoice-number-and-invoice-date-showing-on-preview/
closed by #358
