### ISSUE TITLE
Onboard user with a guided tour

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#396]
As we are implementing an admin pointer [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/395), it might be a nice feature to build this out into a guided tour. Therefore rendering the Wizard obsolete.

As discussed here: https://wpovernight.slack.com/archives/C0121KYKGN6/p1658788826884559

**Comment by alexmigf** [comment]
Marking this as resolved in favor of: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/857
