### ISSUE TITLE
Invoices not sent out after last update

### ISSUE THREAD

**Issue by Ver3** [wpovernight/woocommerce-pdf-invoices-packing-slips#40]
Where do I start to find the problem? Sadly there is no 'sent items' folder in WP.

**Comment by Spreeuw** [comment]
You can install [WP Mail Logging](https://wordpress.org/plugins/wp-mail-logging/) to get a 'sent items' like folder. This will allow you to track emails being sent. Are no emails sent at all or is the PDF not attached? Do you see any errors in your PHP error log? Can you manually create a PDF from the backend? Let me know what you find!

**Comment by Ver3** [comment]
Hi Spreeuw, thank you so much for getting back to me so quickly. I'll try the plugin you suggested. To answer you questions: No errors, manually creating a PDF is no problem. Sometimes the mail is sent (always with attachment as it should be) sometimes they are not.

I'll get back to you, thank you so far.

**Comment by Spreeuw** [comment]
@Ver3 any news regarding this issue?

**Comment by Ver3** [comment]
@Spreeuw Thank you for following up Ewout and apologies for forgetting to update you. Using a SMTP plugin for WP solved the issue. It had nothing to do with your excellent plugin. Cheers!
