### ISSUE TITLE
Open Sans striketrough position

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#41]
Striketrough / line-through position of Open Sans is too high, adjusting ascender & descender values affects line height. See: https://github.com/dompdf/dompdf/issues/1557

**Comment by slaFFik** [comment]
@Spreeuw Would be nice to have this fixed. We faced with this and fixed by removing `0.7` in `/vendor/dompdf/dompdf/src/Renderer/Text.php:151`: 
```php
 $deco_y += $base * 0.7 + $linethrough_offset;
```

**Comment by Johnny99211** [comment]
@slaFFik Thanks too! That was a ugly issue. Hopefully this get fixed in the next release.

**Comment by Spreeuw** [comment]
fixed in dompdf 0.8.3, which will be included in the next release of this plugin too: e0ccf8466fe368bb4946e87f53321878223678c4
