### ISSUE TITLE
JavaScript on unrelated admin pages

### ISSUE THREAD

**Issue by DavidAnderson684** [wpovernight/woocommerce-pdf-invoices-packing-slips#426]
This JS is appearing on all pages (not just relevant ones) in the WP dashboard:

```
<script type="text/javascript">
jQuery( function( $ ) {
	$('#wpo-wcpdf-settings select#paper_size').append($('<option>', {
		value: '72mm',
		text: '72mm'
	}));
	$('#wpo-wcpdf-settings select#paper_size').val('72mm');
});

</script>
```

**Comment by alexmigf** [comment]
@DavidAnderson684 I'm not finding this in the inspector or in the plugin code, are you sure this isn't a custom snippet?

**Comment by alexmigf** [comment]
Not sure what that is.

**Comment by DavidAnderson684** [comment]
Looks like it's a custom template that was built for someone. I don't remember how it ended up on my testing site. I will just remove it! Sorry!
