### ISSUE TITLE
Allow formatting HTML tags for product titles

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#428]
Currently, after merging #408, we strip all the HTML tags for the product titles on the PDF documents. However, there are some cases when the common formatting HTML tags are desirable, like the case reported for [this user](https://wordpress.org/support/topic/html-tags-in-pdf/), in which they're applying styles directly in the product titles, like this:

![image](https://user-images.githubusercontent.com/38109855/198010111-fb3bb90d-45c3-46a8-af89-2dabe0e4fec0.png)

**Comment by alexmigf** [comment]
Like we discuss on Slack, this issue appears to be related to some code introduced in this PR https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/408. We need to revert that code to the previous state.
