### ISSUE TITLE
Georgian (utf8) letters don't display correctly

### ISSUE THREAD

**Issue by sandrodz** [wpovernight/woocommerce-pdf-invoices-packing-slips#43]
I've modified style.css to include dejavusans font for Georgian letters.
Unfortunately pdf still doesn't display correctly.

![screen shot 2017-12-13 at 4 07 30 pm](https://user-images.githubusercontent.com/8479569/33938193-f3334276-e01f-11e7-981f-028371782214.png)

**Comment by Spreeuw** [comment]
AFAIK Georgian characters are supported by the Open Sans font. The fact that it displays the ??? suggests that you may not have PHP MB String/mb_string extension installed on your server.
Can you check this in the System Configuration table under WooCommerce > PDF Invoices > Status?

**Comment by sandrodz** [comment]
@Spreeuw 

Open Sans font doesn't display `???` but `[]` instead. Maybe that can provide a clue...

![screen shot 2017-12-14 at 12 38 05 am](https://user-images.githubusercontent.com/8479569/33961321-0a4b3f76-e067-11e7-9a6e-9c8fa2c2ad94.png)


<img width="1019" alt="screen shot 2017-12-14 at 12 36 51 am" src="https://user-images.githubusercontent.com/8479569/33961281-dfd87c72-e066-11e7-8fae-ea6203a30e94.png">

**Comment by Spreeuw** [comment]
Hi! Apologies, my first comment that Open Sans supports Georgian characters is indeed incorrect. It looks like DejaVuSans does not support it either.

However, doing a quick test with the following CSS:
``` css
@import url(https://fonts.googleapis.com/earlyaccess/notoserifgeorgian.css);
body {
    font-family: 'Noto Serif Georgian', serif;
}
```
Actually did work, which demonstrates that you just need to find a suitable font.
Note that while the above method works well to demonstrate that the plugin+dompdf is able to process georgian characters, in practice you can't use webfonts in this fashion. The reason for this is that dompdf [does not support numeric font weights](https://github.com/dompdf/dompdf/issues/675). It also looks like the above font does not support latin characters, so you will need to find a font that has both.
More information about custom fonts is in the documentation: [Using custom fonts](http://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/using-custom-fonts/)
