### ISSUE TITLE
Fatal error: Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found

### ISSUE THREAD

**Issue by A-Koutiney** [wpovernight/woocommerce-pdf-invoices-packing-slips#432]
2022-10-26T07:41:44+00:00 CRITICAL Fatal error: Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)
2022-10-26T08:29:21+00:00 CRITICAL Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)
2022-10-26T10:07:23+00:00 CRITICAL Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)
2022-10-26T10:07:24+00:00 CRITICAL Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)
2022-10-26T10:13:44+00:00 CRITICAL Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)
2022-10-26T10:13:45+00:00 CRITICAL Class 'WPO\WC\PDF_Invoices\Compatibility\Order' not found (/var/www/vhosts/test.nl/httpdocs/wp-content/themes/test/woocommerce/pdf/test/invoice.php:106)

**Comment by alexmigf** [comment]
Hi @A-Koutiney 

Can you post your template code here? It seems you're running legacy template code.

**Comment by A-Koutiney** [comment]
`<?php if (!defined('ABSPATH')) {
    exit;
} // Exit if accessed directly ?>

<?php
$is_reseller = $this->order->get_user()->has_cap('reseller_gold');

if ($is_reseller) {
    $style = " style='width: 12.5% !important;' ";
} else {
    $style = " style='width: 25% !important;' ";
}
?>

<?php do_action('wpo_wcpdf_before_document', $this->get_type(), $this->order); ?>

<table class="head container">
    <tr>
        <td class="header">
            <?php
            if ($this->has_header_logo()) {
                $this->header_logo();
            } else {
                echo $this->get_title();
            }
            ?>
        </td>
        <td class="shop-info">
            <?php do_action('wpo_wcpdf_before_shop_name', $this->get_type(), $this->order); ?>
            <div class="shop-name"><h3><?php $this->shop_name(); ?></h3></div>
            <?php do_action('wpo_wcpdf_after_shop_name', $this->get_type(), $this->order); ?>
            <?php do_action('wpo_wcpdf_before_shop_address', $this->get_type(), $this->order); ?>
            <div class="shop-address"><?php $this->shop_address(); ?></div>
            <?php do_action('wpo_wcpdf_after_shop_address', $this->get_type(), $this->order); ?>
        </td>
    </tr>
</table>

<?php do_action('wpo_wcpdf_before_document_label', $this->get_type(), $this->order); ?>

<h1 class="document-type-label">
    <?php if ($this->has_header_logo()) {
        echo $this->get_title();
    } ?>
</h1>

<?php do_action('wpo_wcpdf_after_document_label', $this->get_type(), $this->order); ?>

<table class="order-data-addresses">
    <tr>
        <td class="address billing-address">
            
            <?php do_action('wpo_wcpdf_before_billing_address', $this->get_type(), $this->order); ?>
            <?php $this->billing_address(); ?>
            <?php do_action('wpo_wcpdf_after_billing_address', $this->get_type(), $this->order); ?>
            <?php if (isset($this->settings['display_email'])) : ?>
                <div class="billing-email"><?php $this->billing_email(); ?></div>
            <?php endif; ?>
            <?php if (isset($this->settings['display_phone'])) : ?>
                <div class="billing-phone"><?php $this->billing_phone(); ?></div>
            <?php endif; ?>
        </td>
        <td class="address shipping-address">
            <?php if ($this->show_shipping_address()) : ?>
                <h3><?php _e('Ship To:', 'woocommerce-pdf-invoices-packing-slips'); ?></h3>
                <?php do_action('wpo_wcpdf_before_shipping_address', $this->get_type(), $this->order); ?>
                <?php $this->shipping_address(); ?>
                <?php do_action('wpo_wcpdf_after_shipping_address', $this->get_type(), $this->order); ?>
                <?php if (isset($this->settings['display_phone'])) : ?>
                    <div class="shipping-phone"><?php $this->shipping_phone(); ?></div>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td class="order-data">
            <table>
                <?php do_action('wpo_wcpdf_before_order_data', $this->get_type(), $this->order); ?>
                <?php if (isset($this->settings['display_number'])) : ?>
                    <tr class="invoice-number">
                        <th><?php echo $this->get_number_title(); ?></th>
                        <td><?php $this->invoice_number(); ?></td>
                    </tr>
                <?php endif; ?>
                <?php if (isset($this->settings['display_date'])) : ?>
                    <tr class="invoice-date">
                        <th><?php echo $this->get_date_title(); ?></th>
                        <td><?php $this->invoice_date(); ?></td>
                    </tr>
                <?php endif; ?>
                <tr class="order-number">
                    <th><?php _e('Order Number:', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
                    <td><?php $this->order_number(); ?></td>
                </tr>
                <tr class="order-date">
                    <th><?php _e('Order Date:', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
                    <td><?php $this->order_date(); ?></td>
                </tr>
                <tr class="payment-method">
                    <th><?php _e('Payment Method:', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
                    <td><?php $this->payment_method(); ?></td>
                </tr>
                <?php
                if ( $this->is_refund( $this->order ) ) {
                    $parent_order = $this->get_refund_parent( $this->order );
                    $payment_method = WPO\WC\PDF_Invoices\Compatibility\Order::get_prop( $parent_order, 'payment_method', 'view' );
                } else {
                    $payment_method = WPO\WC\PDF_Invoices\Compatibility\Order::get_prop( $this->order, 'payment_method', 'view' );
                }
                if ($payment_method === 'cod') {
                    ?>
                    <tr class="payment-term">
                        <th>Betaaltermijn:</th>
                        <td>30 dagen</td>
                    </tr>
                <?php } ?>
                <?php do_action('wpo_wcpdf_after_order_data', $this->get_type(), $this->order); ?>
            </table>
        </td>
    </tr>
</table>

<?php do_action('wpo_wcpdf_before_order_details', $this->get_type(), $this->order); ?>

<table class="order-details">
    <thead>
    <tr>
        <th class="product"><?php _e('Product', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
        <th class="quantity" <?= $style ?>><?php _e('Quantity', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
        <?php if ($is_reseller) { ?>
            <th class="gross" <?= $style ?>><?php _e('Bedrag', 'lioncards'); ?></th>
            <th class="discount" <?= $style ?>><?php _e('Discount', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
        <?php } ?>
        <th class="price" <?= $style ?>><?php _e('Price', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->get_order_items() as $item_id => $item) : ?>
        <?php
        if ($is_reseller) {
            // Get variation ID if available, else get product ID
            $meta_lookup_id = $item['item']->get_variation_id() ?: $item['item']->get_product_id();
            
            $price_before_discount = get_post_meta($meta_lookup_id, '_price', true);
            $discount = get_post_meta($meta_lookup_id, '_role_base_price_reseller_gold', true);
            $discount = unserialize($discount);
        }
        ?>
        <tr class="<?php echo apply_filters('wpo_wcpdf_item_row_class', 'item-' . $item_id, $this->get_type(), $this->order, $item_id); ?>">
            <td class="product">
                <?php $description_label = __('Description', 'woocommerce-pdf-invoices-packing-slips'); // registering alternate label translation ?>
                <span class="item-name"><?php echo $item['name']; ?></span>
                <?php do_action('wpo_wcpdf_before_item_meta', $this->get_type(), $item, $this->order); ?>
                <span class="item-meta"><?php echo $item['meta']; ?></span>
                <dl class="meta">
                    <?php $description_label = __('SKU', 'woocommerce-pdf-invoices-packing-slips'); // registering alternate label translation ?>
                    <?php if (!empty($item['sku'])) : ?>
                        <dt class="sku"><?php _e('SKU:', 'woocommerce-pdf-invoices-packing-slips'); ?></dt>
                        <dd class="sku"><?php echo $item['sku']; ?></dd><?php endif; ?>
                    <?php if (!empty($item['weight'])) : ?>
                        <dt class="weight"><?php _e('Weight:', 'woocommerce-pdf-invoices-packing-slips'); ?></dt>
                        <dd class="weight"><?php echo $item['weight']; ?><?php echo get_option('woocommerce_weight_unit'); ?></dd><?php endif; ?>
                </dl>
                <?php do_action('wpo_wcpdf_after_item_meta', $this->get_type(), $item, $this->order); ?>
            </td>
            <td class="quantity" <?= $style ?>><?php echo $item['quantity']; ?></td>
            <?php if ($is_reseller) { ?>
                <td class="gross" <?= $style ?>><?php echo wc_price($price_before_discount, []); ?></td>
                <td class="discount" <?= $style ?>>
                    <?php
                    if ($discount['discount_type'] === 'percentage_decrease') {
                        echo $discount['discount_value'] . "%";
                    } else if ($discount['discount_type'] === 'fixed_decrease') {
                        echo wc_price($discount['discount_value']);
                    }
                    ?>
                </td>
            <?php } ?>
            <td class="price" <?= $style ?>><?php echo $item['order_price']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr class="no-borders">
        <td class="no-borders">
            <div class="document-notes">
                <?php do_action('wpo_wcpdf_before_document_notes', $this->get_type(), $this->order); ?>
                <?php if ($this->get_document_notes()) : ?>
                    <h3><?php _e('Notes', 'woocommerce-pdf-invoices-packing-slips'); ?></h3>
                    <?php $this->document_notes(); ?>
                <?php endif; ?>
                <?php do_action('wpo_wcpdf_after_document_notes', $this->get_type(), $this->order); ?>
            </div>
            <div class="customer-notes">
                <?php do_action('wpo_wcpdf_before_customer_notes', $this->get_type(), $this->order); ?>
                <?php if ($this->get_shipping_notes()) : ?>
                    <h3><?php _e('Customer Notes', 'woocommerce-pdf-invoices-packing-slips'); ?></h3>
                    <?php $this->shipping_notes(); ?>
                <?php endif; ?>
                <?php do_action('wpo_wcpdf_after_customer_notes', $this->get_type(), $this->order); ?>
            </div>
        </td>
        <td class="no-borders" colspan="<?= $is_reseller ? '4' : '2' ?>">
            <table class="totals">
                <tfoot>
                <?php foreach ($this->get_woocommerce_totals() as $key => $total) : ?>
                    <tr class="<?php echo $key; ?>">
                        <th class="description"><?php echo $total['label']; ?></th>
                        <td class="price"><span class="totals-price"><?php echo $total['value']; ?></span></td>
                    </tr>
                <?php endforeach; ?>
                </tfoot>
            </table>
        </td>
    </tr>
    </tfoot>
</table>

<pre>
<?php
foreach ($this->get_order_items() as $order_item) {
    print_r($order_item->item);
}
?>
</pre>

<div class="bottom-spacer"></div>

<?php do_action('wpo_wcpdf_after_order_details', $this->get_type(), $this->order); ?>

<?php if ($this->get_footer()) : ?>
    <div id="footer">
        
        <?php $this->footer(); ?>
        
    </div>
<?php endif; ?>

<?php do_action('wpo_wcpdf_after_document', $this->get_type(), $this->order); ?>
`

**Comment by alexmigf** [comment]
Replace lines 102 to 107 with this:

```php
if ( $this->is_refund( $this->order ) ) {
	$parent_order = $this->get_refund_parent( $this->order );
	$payment_method = $parent_order->get_payment_method();
} else {
	$payment_method = $this->order->get_payment_method();
}
```

**Comment by A-Koutiney** [comment]
It is working. Thanks a lot!
