### ISSUE TITLE
missing nonce on hide link in admin section

### ISSUE THREAD

**Issue by dpeyou** [wpovernight/woocommerce-pdf-invoices-packing-slips#449]
How to reproduce

1. Go to https://localhost/wordpress/wp-admin/admin.php?page=wpo_wcpdf_options_page&tab=general
2. Find a popup about setup an email attachment
3. Press "Hide this message"
4. Check the HTTP request, the HTTP request doesn't have CSRF nonce token when importing setting

**Comment by alexmigf** [comment]
@jhosagid7 can you pick this issue please? Any questions let me know on Slack.
