### ISSUE TITLE
Select order items to generate PDF + Template selection

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#451]
A customer suggested a way to select order items to generate a PDF, and also a selector for the template, both in the order page.

**Comment by MohamadNateqi** [comment]
@alexmigf 
What do you think about this:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/58e0afc2-b17a-4724-b895-2ff224f8d174)

**Comment by alexmigf** [comment]
Looks great, but looking at this I think this should be moved to the Professional extension.

**Comment by MohamadNateqi** [comment]
Yeah, I forgot to mention that. It's better to be in the Professional extension.
Also, maybe later we can add UBL to it.

**Comment by alexmigf** [comment]
I'm not sure if UBL should be a target for this, but yes, we can see that later.

**Comment by MohamadNateqi** [comment]
Do you think we need to display the PDF documents created using this in the "PDF document data" metabox?

Also, I'll add a warning below the selected document type for situations where the credit note has been selected, but there is no invoice already.

If you agree, I proceed with developing this for the professional extension.

**Comment by MohamadNateqi** [comment]
This issue has been moved to [here](https://github.com/wpovernight/woocommerce-pdf-ips-pro/issues/281).
