### ISSUE TITLE
Display the PDF document numbers in the WC Analytics

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#452]
A user in the forums asked us how to display the Invoice number in the WC Analytics Orders report [here](https://wordpress.org/support/topic/invoice-number-in-woocommerce-analytics/?view=all#post-16306048).

Because this Analytics use JavaScript instead of PHP we need to investigate how to do this properly.

Reference: https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/

**Comment by dpeyou** [comment]
I get "permission denied" when trying to clone the WC-analytics repository as per the 2nd link above:
`git clone git@github.com:woocommerce/woocommerce-admin.git`

Permission denied
`git@github.com: Permission denied (publickey).`
