### ISSUE TITLE
Deprecated WooCommerce Subscription hooks used

### ISSUE THREAD

**Issue by bverhoeven** [wpovernight/woocommerce-pdf-invoices-packing-slips#460]
Hi :wave:

Hope this is the right place to report issues with the plugin.

We're trying to use this plugin in combination with the "official" [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) plugin, version 4.7.0. The authors of that plugin have deprecated a hook used by this plugin in such a way that renewing subscriptions becomes impossible.

When renewing a subscription (interactively, but this also affects automatic renewals) the following notice is displayed:

> We couldn't create a renewal order for your subscription, please try again.

This is caused by a WP_Error thrown by the subscription plugins filter deprecator:

> Hook wcs_renewal_order_meta is deprecated since version wcs-core 2.5.0! Use wc_subscriptions_renewal_order_data instead

The action is added at: 

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/5048ca51bcfed8db1eba4e0f5ae72ecdbf01bfa6/includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php#L20

I can confirm that temporarily removing the action (in addition to the one from https://wordpress.org/support/topic/deprecated-subscription-hooks-prevent-subscription-renewal/), fixes the renewal issues.

**Comment by alexmigf** [comment]
Thank you for letting us know about this issue @bverhoeven, we will provide a fix soon.

**Comment by alexmigf** [comment]
@jhosagid7 we need to update the hook in our plugin but keep compatibility with prior versions from `> 2.0` to `2.5` here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/5048ca51bcfed8db1eba4e0f5ae72ecdbf01bfa6/includes/compatibility/class-wcpdf-compatibility-third-party-plugins.php#L16-L23

Also check if there is also a replacement for the `wcs_resubscribe_order_meta` hook and do the same.

**Comment by lkraav** [comment]
We are using both this plugin, and SON with WCS, and subscriptions are renewing fine, even though yes, the deprecated meta notice triggers a lot right now.

Could use more detail on the WP_Error. We are tracking all PHP errors with Sentry and such has not shown up.

**Comment by bverhoeven** [comment]
Thanks for your quick response! 

For context, we're not running this plugin in production yet, and are still working on activating subscription features with a self-hosted subscription platform, hence the need to test manual renewals.

I just noticed that this error only occurs when running with `WP_DEBUG` set, as that, by default, causes `wc_deprecated_hook` to trigger errors using `trigger_error()` so that could explain why you aren't seeing it in production environments. Apologies for leaving that out.

I understand this lowers the severity of this issue, and I could probably work around it for now, but I'd rather keep debug mode set on my development setup.

For clarification, in my case, the error is returned but never thrown and never visible to the customer, renewals simply fail. I had added some debugging code to determine the actual error, and the error is returned through the following chain:

* WCS_Early_Renewal_Modal_Handler::process_early_renewal_request()
   * wcs_create_renewal_order($subscription), returning WP_Error('renewal-order-error', [deprecation message]);
     * wcs_create_order_from_subscription($subscription, 'renewal_order'), returning WP_Error('new-order-error', [deprecation message]);
       * wcs_copy_order_meta (eventually) throwing an Exception with the deprecation message set.

The error I'm seeing (var_dump()'ed) matches that chain:

```
object(WP_Error)#9494 (3) {
  ["errors"]=>
  array(1) {
    ["renewal-order-error"]=>
    array(1) {
      [0]=>
      string(153) "Hook wcs_renewal_order_meta_query is deprecated since version subscriptions-core 2.5.0! Use wc_subscriptions_renewal_order_data instead."
    }
  }
  ["error_data"]=>
  array(0) {
  }
  ["additional_data":protected]=>
  array(0) {
  }
}
```

The user doesn't see this error as `process_early_renewal_request` hides any errors and simply shows a generic mesasge:
     
```php
$renewal_order = wcs_create_renewal_order($subscription);

if (!wcs_is_order($renewal_order)) {
	wc_add_notice(__("We couldn't create a renewal order for your subscription, please try again.", 'woocommerce-subscriptions'), 'error');
	self::redirect();
}
```

**Comment by bverhoeven** [comment]
Hey, thanks. 

I understand that a var_dump() isn't going to tell much about the path taken, just wanted to clarify the type of WP_Error that was being returned.

> I think your renewal is failing for some other reason, but it goes through enough to trigger this (I think unrelated) deprecation warning.

I'm sorry, I have to disagree.

As I mentioned before, removing the `wcs_renewal_order_meta` action, which (in my case) is only registered by _this_ plugin, resolves the error. 

I've added some more debugging, and the exception as caught in `wcs_copy_order_meta()` (which causes the rest of the chain to fail) also refers to the `trigger_error` that is raised by `wc_deprecated_hook`:

```
ErrorException: Hook wcs_renewal_order_meta is <strong>deprecated</strong> since version wcs-core 2.5.0! Use wc_subscriptions_renewal_order_data instead. in /var/www/html/wp-includes/functions.php:5758
Stack trace:
#0 [internal function]: {closure}(16384, 'Hook wcs_renewa...', '/var/www/html/w...', 5758)
#1 /var/www/html/wp-includes/functions.php(5758): trigger_error('Hook wcs_renewa...', 16384)
#2 /var/www/html/wp-content/plugins/woocommerce/includes/wc-deprecated-functions.php(79): _deprecated_hook('wcs_renewal_ord...', 'wcs-core 2.5.0', 'wc_subscription...', '')
#3 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-deprecated-functions.php(274): wc_deprecated_hook('wcs_renewal_ord...', 'wcs-core 2.5.0', 'wc_subscription...', NULL)
#4 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-data-copier.php(414): wcs_deprecated_hook('wcs_renewal_ord...', 'wcs-core 2.5.0', 'wc_subscription...')
#5 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-data-copier.php(123): WC_Subscriptions_Data_Copier->apply_deprecated_filter(Array)
#6 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-data-copier.php(80): WC_Subscriptions_Data_Copier->copy_data()
#7 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-order-functions.php(156): WC_Subscriptions_Data_Copier::copy(Object(WC_Subscription), Object(WC_Order), 'renewal_order')
#8 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-order-functions.php(190): wcs_copy_order_meta(Object(WC_Subscription), Object(WC_Order), 'renewal_order')
#9 /var/www/html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php(29): wcs_create_order_from_subscription(Object(WC_Subscription), 'renewal_order')
#10 /var/www/html/wp-content/plugins/woocommerce-subscriptions/includes/early-renewal/class-wcs-early-renewal-modal-handler.php(135): wcs_create_renewal_order(Object(WC_Subscription))
#11 /var/www/html/wp-includes/class-wp-hook.php(308): WCS_Early_Renewal_Modal_Handler::process_early_renewal_request('')
#12 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#13 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#14 /var/www/html/wp-settings.php(639): do_action('wp_loaded')
#15 /var/www/html/wp-config.php(144): require_once('/var/www/html/w...')
#16 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#17 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')
#18 /var/www/html/index.php(17): require('/var/www/html/w...')
#19 {main}
```

This exception is caught by  `wcs_copy_order_meta` which converts it to the WP_Error that I mentioned in my previous post,

```php
} catch (Exception $e) {
  // There was an error adding the subscription
  $transaction->rollback();
  return new WP_Error('new-order-error', $e->getMessage());
}
```

**Comment by bverhoeven** [comment]
Okay, figured out why it's throwing errors. An unrelated plugin is doing:

```php
if (WP_DEBUG) {
    set_error_handler(function ($severity, $message, $file, $line) {
        if (error_reporting() & $severity) {
            throw new ErrorException($message, 0, $severity, $file, $line);
        }
    });
}
```

So, yes, the error is caused by the deprecation warning, but this should normally not cause any issues.

The deprecation issue still stands though, and I feel it would still be good to have it fixed.

**Comment by lkraav** [comment]
Yep, that was exactly going to by next guess - something has changed error level severity. OK glad we got it sorted out, now team wpovernight has a better idea of the severity here. Fortunately it's benign, but I gotta say I'm getting quite tired of my Action Scheduler cronjobs spitting this out in my email for weeks now, so hopefully a patch release is coming soon! :pray:
