### ISSUE TITLE
Fatal error: Allowed memory size of XX bytes exhausted

### ISSUE THREAD

**Issue by sandrodz** [wpovernight/woocommerce-pdf-invoices-packing-slips#47]
wp-admin has become inaccessible.

error:
```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /www/plugandpay.test/public/wordpress/wp-includes/functions.php on line 1872

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

this happens when uploads dir is not writable.

1872 is mentioning caching, and this was the hint that problem was related to uploads dir

<img width="1207" alt="screen shot 2018-05-14 at 2 10 09 pm" src="https://user-images.githubusercontent.com/8479569/39991444-a4c544b2-5780-11e8-8868-37e0757ee8e0.png">

Plugin should be improved to deal with unwritable uploads dir a in a better way.

**Comment by Spreeuw** [comment]
Hi! Thanks for reporting! I haven't seen this in testing before and haven't had any reports of this yet either. Are you saying this happens when the entire uploads folder is not writable by plugins? Is this on a vanilla WP installation or are you using any deployment tools?
Thanks!
Ewout

**Comment by Spreeuw** [comment]
@sandrodz could you test if this commit fixes your issue? https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/9933e645a64e40759ce8422ed25cc663df36829c

**Comment by Spreeuw** [comment]
@sandrodz have you been able to take a look at the patch? I'd love to hear your feedback so I know if I can indeed close this issue!

**Comment by sandrodz** [comment]
Hi, just checked, it fixes issue.

**Comment by Spreeuw** [comment]
awesome, thanks!
