### ISSUE TITLE
Fonts used in invoices does not support Arabic characters and lack of RTL attention

### ISSUE THREAD

**Issue by shadigaafar** [wpovernight/woocommerce-pdf-invoices-packing-slips#479]
Current fonts used does not support Arabic characters.... all you can see is squares. also invoices does not support RTL. 

Exmaple: 
![image](https://user-images.githubusercontent.com/74800166/220086423-394c10ae-a604-48c1-9c5d-c9074165c2e2.png)

**Comment by YordanSoares** [comment]
Hi @shadigaafar,

We already support Arabic, just not by default. You will need a separate extension that will give you the ability to create a right-to-left layout and supports an Arabic font, which you can download here: [woocommerce-pdf-ips-mpdf.2.4.1.zip](https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/releases/download/v2.4.1/woocommerce-pdf-ips-mpdf.2.4.1.zip)

You just need to install it as a regular plugin and activate it. Finally, if you need to activate the RTL layout, select the **Simple RTL** template in **WooCommerce > PDF Invoices > General > Choose a template**.

For now, I'm closing this issue, but feel free to [create a new topic](https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips/#new-topic-0) in WordPress.org if you have more questions or you need any help with the plugin.

**Comment by shadigaafar** [comment]
At least you should inform user when the langauge of website is Arabic that their is another extension to download.

**Comment by YordanSoares** [comment]
That is a good idea, @shadigaafar. I will share your suggestion with the team. Thank you.
