### ISSUE TITLE
Conflict with WooCommerce Lightspeed POS

### ISSUE THREAD

**Issue by thenissengroup** [wpovernight/woocommerce-pdf-invoices-packing-slips#48]
When the packing slip module is enabled, the Lightspeed plugin (https://docs.woocommerce.com/document/woocommerce-lightspeed-pos/) no longer reduces inventory when an order is placed.

**Comment by Spreeuw** [comment]
Since WooCommerce Lightspeed is a commercial plugin, I can't test this myself. Do you see any fatal errors in the PHP error log?

**Comment by thenissengroup** [comment]
Actually I didn’t see any errors.  We just switched to a different plugin, and that seemed to work.  Thank you for all of your help!

-Jay

**Comment by Spreeuw** [comment]
Thanks! Glad to hear the issue is resolved.
