### ISSUE TITLE
Display a notice about the existence of the mPDF extension when the site language is RTL

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#480]
The default PDF engine we use is not compatible with RTL, but we have an extension that switch the PDF engine with mPDF that it is compatible with RTL, but also includes a font compatible with Arabic characters.

[This user](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/479#issuecomment-1437124865) suggested displaying a notice about the existence of the mPDF extension when the site language is Arabic, but would add an `OR` extra check to also display the notice if the language is from the RTL script language family.

**Comment by DavidAnderson684** [comment]
(I am subscribing to this issue since it'll make sense for me to put the same notice in the PrintNode plugin where the same situation exists - defaults to DomPDF, mPDF available via an add-on).
