### ISSUE TITLE
Integrate UBL code from extension

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#481]
Currently we offer an extension to add the UBL Invoice, we should include that code inside the plugin and provide this feature as beta.

**Comment by alexmigf** [comment]
Some remarks:

* Detect the current extension, deactivate and ask for deletion
* UBL feature should be disabled by default, can be enabled on status page
* Add UBL settings to import/export tool

**Comment by alexmigf** [comment]
Don't you think we should treat the UBL as a separated document? Mixing it with the current Invoice could be problematic no? Because in the end it's a different kind of document.

**Comment by Terminator-Barbapapa** [comment]
Wikipedia: _Universal Business Language (UBL) is an open library of standard electronic XML business documents for procurement and transportation such as purchase orders, invoices, transport logistics and waybills._

So I don't view at as a separate document, but only a different version. My personal accounting software (MoneyBird) handles this in the same way. It provides a way to generate the invoice and gives me the option to send/download the invoice as a PDF a UBL or both.

Also if we are going to expand this and provide the UBL version for our other documents I think it will get cluttered if the UBLs are all separate documents.

**Comment by alexmigf** [comment]
Ok, I agree with your point.

How it will be handled in the customizer if it's attached to the Invoice object?

**Comment by Terminator-Barbapapa** [comment]
Looking at this more closely I think the UBL tab needs to remain. I think all of the general UBL settings can move though. The 'Company name', 'VAT number' and 'CoC number' settings can move to the General tab. The 'Include encrypted PDF' can move to each respective document tab. And for the 'Attach to' setting we could work with tabs like this:

<img width="633" alt="Schermafbeelding 2023-05-12 om 16 43 14" src="https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/19350150/d98e6d7c-a42c-4054-a4b8-bfcba1322910">

We would then keep the UBL tab for the classifying of the tax rates. And we can include things like the UBL templates and UBL customizer there for the extensions.

**Comment by alexmigf** [comment]
I agree, I think it's the better way to do it.

**Comment by alexmigf** [comment]
Like I mention here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/481#issuecomment-1438708820

I think we should disable the UBL by default, what you think? If that's the case we should add a setting to enable it under the Status page.

**Comment by Terminator-Barbapapa** [comment]
Perhaps we can add an extra 'Enable UBL' setting to each document? And display the extra document settings based on this checkbox. Also if any of the documents have UBL enabled we show the UBL settings tab.

<img width="548" alt="Scherm­afbeelding 2023-05-26 om 14 34 42" src="https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/19350150/319f2fb2-6e99-4a10-b774-030a557b4e6b">

Also I think we can add an 'Enable UBL' option in the setup wizard.
