### ISSUE TITLE
plugin not working 

### ISSUE THREAD

**Issue by khizer253** [wpovernight/woocommerce-pdf-invoices-packing-slips#490]
we have updated the WordPress up to 6.1 and php up to php8 and the plugin gives an error that php gd extension is required.  How to add hsn code in product and it is printed in order form and on the invoice.
Exception: The PHP GD extension is required, but is not installed.
/var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/lib/Cpdf.php (5813)
#0 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Adapter/CPDF.php(669): Dompdf\Cpdf->addPngFromFile()
#1 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer/Image.php(65): Dompdf\Adapter\CPDF->image()
#2 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(289): Dompdf\Renderer\Image->render()
#3 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(128): Dompdf\Renderer->_render_frame()
#4 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(195): Dompdf\Renderer->render()
#5 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(195): Dompdf\Renderer->render()
#6 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(195): Dompdf\Renderer->render()
#7 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(195): Dompdf\Renderer->render()
#8 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Renderer.php(195): Dompdf\Renderer->render()
#9 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/FrameReflower/Page.php(149): Dompdf\Renderer->render()
#10 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow()
#11 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#12 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-pdf-maker.php(54): Dompdf\Dompdf->render()
#13 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(797): WPO\WC\PDF_Invoices\PDF_Maker->output()
#14 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/documents/abstract-wcpdf-order-document.php(862): WPO\WC\PDF_Invoices\Documents\Order_Document->get_pdf()
#15 /var/www/wordpress/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-main.php(403): WPO\WC\PDF_Invoices\Documents\Order_Document->output_pdf()
#16 /var/www/wordpress/wp-includes/class-wp-hook.php(308): WPO\WC\PDF_Invoices\Main->generate_pdf_ajax()
#17 /var/www/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /var/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#19 /var/www/wordpress/wp-admin/admin-ajax.php(188): do_action()
#20 {main}

**Comment by alexmigf** [comment]
Could you paste a screenshot of you page **WooCommerce > PDF Invoices > Status > System Configuration**?

**Comment by alexmigf** [comment]
Closing since we haven't got more information.
