### ISSUE TITLE
2.1.10: override formatted invoice number w/ special characters?

### ISSUE THREAD

**Issue by lkraav** [wpovernight/woocommerce-pdf-invoices-packing-slips#50]
Hi. In some weird cases (admins forget to mark payment complete for months) I have to manually set a past invoice date and number.

For better clarity, I was trying to do "6363.5" or "6363/5", instead of just "63635", but it looks like special characters are getting stripped out of the formatted string.

Am I missing something? Should I be able to write almost whatever into the "unformatted" form field, and have it reflected on the PDF invoice? Is this a bug or a feature request?

**Comment by Spreeuw** [comment]
Hi! The "unformatted" bit refers to the fact that this should be the bare invoice number, which is treated as an integer. If you need any further formatting, you can set this in the invoice number format settings under WooCommerce > PDF Invoices > Documents > Invoice. This will be saved with the order, so after creating the invoice number you can remove the suffix again. Note that each time you edit the invoice number and re-save, it will also reset the prefix/suffix/padding settings and take the latest instead.
