### ISSUE TITLE
Improve the packing slip number setting

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#501]
Currently, we offer three options to the invoice number setting, including using the order number as invoice number:

![image](https://user-images.githubusercontent.com/38109855/232320002-e2c6a17f-8a78-404c-bfe8-4f5582926971.png)

However, the packing slip number setting does not offer the order number as an option yet:

![image](https://user-images.githubusercontent.com/38109855/232320119-138ce8d4-672d-403f-8ba6-85ede868bba1.png)

**Comment by alexmigf** [comment]
Closing in favor of this https://github.com/wpovernight/woocommerce-pdf-ips-pro/issues/274
