### ISSUE TITLE
Revert overflow-wrap for order data table

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#539]
A while ago we added soms CSS that made it possible to have very long text strings (like URLs) on our PDFs without having them run of the page. This was fixed in the following PR: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/445

However this also affects users that have long labels in the order data table. 

<img width="294" alt="Scherm­afbeelding 2023-07-03 om 13 17 10" src="https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/19350150/b968ef96-c45c-4437-a7bd-fe40384a36a5">

We've gotten multiple support tickets about this. I think it is better to revert this CSS style on the order data table. And to only provide the `overflow-wrap: anywhere;` rule as a code snippet fix for customers that require this on their PDFs, for instance because they display a URL there.

**Comment by MohamadNateqi** [comment]
@Terminator-Barbapapa I think we can fix the label problem without reverting those changes. Adding the below rules will only target the labels and fix that issue:
```
td.order-data table th {
    overflow-wrap: break-word;
}
```
If you agree, I will do this without reverting those changes.

**Comment by Terminator-Barbapapa** [comment]
@MohamadNateqi Perhaps "reverting" was a poor choice of words. But I indeed mean going back to how things were before. This should not only apply to the labels but also to the values of the order data table. Applying `overflow-wrap: break-word;` should work.
