### ISSUE TITLE
Introduce class autoloader

### ISSUE THREAD

**Issue by szepeviktor** [wpovernight/woocommerce-pdf-invoices-packing-slips#544]
Would you be interested in a class autoloader?
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/b0fa8df09bfba974b85df0c4fd2d6d2d74483d3c/readme.txt#L7
It is supported since PHP 5.1.0

**Comment by alexmigf** [comment]
Thank you for your suggestion @szepeviktor . Yes, that's something we should consider for the next releases. You can follow the progress here.

**Comment by szepeviktor** [comment]
All right 🚀 

1. Add the autoloader / use Composer's "classmap" loader
2. Move class instantiation from the end of the class to where is it is called from
