### ISSUE TITLE
How to display custom product metadata in the invoices.

### ISSUE THREAD

**Issue by hacktronics** [wpovernight/woocommerce-pdf-invoices-packing-slips#547]
How to display custom product metadata in the invoices. the get_order_items item does not contain any custom product metadata.

**Comment by alexmigf** [comment]
You can achieve that using our [Premium Templates extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-premium-templates/) and the [customizer](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/using-the-customizer/).

You can use the custom field column:

![Screenshot from 2023-07-14 08-40-58](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/5011b276-abc4-43bf-bce1-b154f572ca69)

Or use the product column with a placeholder:

![Screenshot from 2023-07-14 08-41-56](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/f863366f-d6f5-4963-9ec5-69c383235224)

**Comment by hacktronics** [comment]
Anyway figured it out using the get_post_meta method, you can get the attribute.
`get_post_meta( $item->get_product(), '_custom_product_attribute', true );`
