### ISSUE TITLE
Stale invoice PDF sent with the order email

### ISSUE THREAD

**Issue by squatto** [wpovernight/woocommerce-pdf-invoices-packing-slips#55]
Using ACF, I added a field "Tracking Number" to the orders. I added the tracking number to the invoice PDF like this:

```php
/**
 * If present, output the tracking number on the invoice PDF
 *
 * @param string $type
 * @param \WC_Order $order
 */
function add_tracking_number_to_invoice_pdf($type, \WC_Order $order)
{
    $trackingNumber = get_field('tracking_number', $order->get_id());

    if (strlen($trackingNumber)) {
        ?>
        <tr class="payment-method">
            <th><?php _e('Tracking Number:', 'woocommerce-pdf-invoices-packing-slips'); ?></th>
            <td><?php echo esc_html($trackingNumber); ?></td>
        </tr>
        <?php

    }
}

add_action('wpo_wcpdf_after_order_data', __NAMESPACE__ . '\\add_tracking_number_to_invoice_pdf', 10, 2);
```

It works great if I click "PDF Invoice" from the order info screen. However, when I first enter the tracking number and save+send an email to the customer, a previously-generated PDF is sent to them. This may make more sense if I give you steps to reproduce.

This obviously assumes you have a custom field on your order that outputs on the email template.

1. Order submitted by customer. They receive the PDF invoice by email.
2. Review the order in the admin, enter a value in your custom field, change the status to "Completed", and click the regular "Update" button.
3. A "Completed" email will be sent to the customer, with the PDF invoice attached. However, this PDF invoice is the same one that was attached in step 1. It was _not_ updated with the tracking number that was just entered.
4. You can manually send the customer any emails you want - they'll always receive the same PDF invoice.
5. Manually generate the PDF invoice by clicking the "PDF Invoice" button. This time, the updated invoice will be generated, with the custom field value being shown.
6. Any email you send will now have the custom field value on it, because it's sending the file you generated in step 5.

I can record a video showing you this too, if you would prefer. It seems that the issue could be resolved by regenerating the PDF each time it is attached, rather than sending the file if it already exists. I can dig in and figure out why it's doing that and make a PR if you don't have time 👍 

Thanks!

**Comment by squatto** [comment]
I should note that I have the PDF invoice set to attach to:

* New order (Admin email)
* Processing order
* Completed order
* Refunded order
* Customer invoice / Order details (Manual email)

**Comment by Spreeuw** [comment]
When you press the button to generate a PDF or when you send an email, it is always generated on the fly - it **never** 'reuses' a PDF file. This probably means that the tracking number is saved **_after_** the PDF is sent (in the same request). Could you try saving the order and **_then_** send the PDF?

**Comment by Spreeuw** [comment]
@squatto have you been able to check the above?
