### ISSUE TITLE
Shipping notes not respecting line breaks

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#570]
Because now we allow Shipping notes to be translated, we are removing all HTML tags here:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/559/files#diff-3c27d95148592338471e6af2989845953abad29560a97a4e73b989aaa9d1253fR1098

Maybe we could add a filter to ignore that for customers that require the tags.

**Comment by alexmigf** [comment]
We are receiving more users complaining about this, maybe we should remove the strip function? What do you think @YordanSoares and @MohamadNateqi ?

**Comment by MohamadNateqi** [comment]
@alexmigf It seems to me it's better if we set the default to false.

**Comment by YordanSoares** [comment]
I agree with @MohamadNateqi: We could leave the strip function set to false by default. However, if you think it doesn't have sense, then delete it. I'm fine with either decision.
