### ISSUE TITLE
number format settings note

### ISSUE THREAD

**Issue by dwalkerpriv** [wpovernight/woocommerce-pdf-invoices-packing-slips#589]
Add a note that tells users that when they add/adjust the number format with a suffix or prefix in the document settings, then the new number format will take effect in a new order. this should be done for the Professional docs as well

**Comment by alexmigf** [comment]
Done here https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/998de91aa0747a774bc4013913e58eab1fc189fd

Closing...
