### ISSUE TITLE
PHP: Count issue in phenx 

### ISSUE THREAD

**Issue by Johnny99211** [wpovernight/woocommerce-pdf-invoices-packing-slips#59]
My debug.log gets spammed with a lot of these errors:

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/enwikuna.de/httpdocs/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/vendor/phenx/php-svg-lib/src/Svg/Document.php on line 259`

Maybe you take a look in the next release to add a check if it's an array or object or maybe you change this part.

**Comment by Spreeuw** [comment]
This is an external library, you can report the issue here: https://github.com/PhenX/php-svg-lib/issues
