### ISSUE TITLE
Is there a filter that we can change this part?

### ISSUE THREAD

**Issue by ambisyoso901** [wpovernight/woocommerce-pdf-invoices-packing-slips#61]
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e0ccf8466fe368bb4946e87f53321878223678c4/includes/class-wcpdf-admin.php#L183

**Comment by Spreeuw** [comment]
yes, two lines up... https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e0ccf8466fe368bb4946e87f53321878223678c4/includes/class-wcpdf-admin.php#L181

**Comment by ambisyoso901** [comment]
I tried to change those part using apply filter, but it return me an error. Supply Foreach, forgot the error name, can you help me on this thanks.

**Comment by Spreeuw** [comment]
If you provide your filter I may be able to point out the error

**Comment by ambisyoso901** [comment]
```
add_filter('wpo_wcpdf_listing_actions' , 'ct_wpo_wcpdf_listing_actions', 10, 2);
function ct_wpo_wcpdf_listing_actions($listing_actions, $order){
if(true) {
// in this case hide button
return false;
}
return $listing_actions;

}
```

I just do it like this

**Comment by Spreeuw** [comment]
yes it returned and error because you returned `false` instead of an array. The above example leaves the array intact.

**Comment by ambisyoso901** [comment]
yes, so what I did is empty the array, but there the button would appear empty like this http://prntscr.com/m4g5y2

**Comment by Spreeuw** [comment]
please share the exact code you used, because it appears there's still an error in your code

**Comment by ambisyoso901** [comment]
here is my code:

`add_filter('wpo_wcpdf_listing_actions' , 'ct_wpo_wcpdf_listing', 10, 2);

function ct_wpo_wcpdf_listing($listing_actions, $order){

    $orders = wc_get_order( $order->id );
    $attr_type = "";
    //Get Order Items
    foreach( $orders->get_items() as $item => $item_prd){
        $product = $item_prd->get_product();
        //Check if product have variations
        if($product->is_type('variation')){
            $attr_type = $product->get_variation_attributes()['attribute_type']; //Get specific variations
        }
    }

    //Check if attribute is PDF
    if( $attr_type == "PDF"){
        $listing_actions['invoice']['url'] = '';   //Unset Invoice actions if not URL
        $listing_actions['invoice']['img'] = '';   //Unset Invoice actions if not IMG
        $listing_actions['invoice']['alt'] = '';   //Unset Invoice actions if not ALT
        $listing_actions['invoice']['exists'] = false;   //Unset Invoice actions if not PDF
    }

    return $listing_actions;

}`

**Comment by Spreeuw** [comment]
That explains, you're not removing the actual element, if you follow my example using `unset`, everything should work: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/61#issuecomment-452280184

**Comment by ambisyoso901** [comment]
I will try, and report to you thank you :)

**Comment by ambisyoso901** [comment]
@Spreeuw it works, thank you
