### ISSUE TITLE
Adding output parameter to URL no longer works

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#610]
Adding the `output=html` parameter to the URL no longer works because `html` is not set as a possible output format for the documents. For instance for the invoice here:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e00f82e7c208eda0297520ff373edf8c8520c50e/includes/documents/class-wcpdf-invoice.php#L50

So the following will return false:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e00f82e7c208eda0297520ff373edf8c8520c50e/includes/class-wcpdf-settings.php#L531

All documents have to be updated (including bulk documents).

**Comment by alexmigf** [comment]
I think it was fixed [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/608)? Do you have the branch updated?

**Comment by Terminator-Barbapapa** [comment]
Sorry, you are absolutely right. I was still on the UBL branch.
