### ISSUE TITLE
Request to add watermark for Refunded and Cancelled order.

### ISSUE THREAD

**Issue by sayful1** [wpovernight/woocommerce-pdf-invoices-packing-slips#62]
Currently there is no way to identify refunded and cancelled order. It will be great if you add watermark for refunded and cancelled order.

**Comment by Spreeuw** [comment]
You can print the order status of an order in the invoice using one of the [template action hooks](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/pdf-template-action-hooks/).
Example:
`
add_action( 'wpo_wcpdf_after_document_label', 'wpo_wcpdf_refunded_cancelled_watermark', 10, 2);
function wpo_wcpdf_refunded_cancelled_watermark( $template_type, $order ) {
	$print_statuses = array( 'refunded', 'cancelled', 'failed' );
	$order_status = $order->get_status();
	if (in_array($order_status, $print_statuses)) {
		printf('<h1 class="order-status">%s</h1>',wc_get_order_status_name($order_status));
	}
}
`
