### ISSUE TITLE
The `&output=html` parameter does not work with pretty links

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#620]
Although the **Output to HTML** setting does work with pretty links, the `&output=html` parameter does not.

**Comment by alexmigf** [comment]
In which version did you faced the issue? Did you test with the last `main`?

**Comment by YordanSoares** [comment]
@alexmigf tested with both public release and `main`, same issue: 

> You do not have sufficient permissions to access this page. Reason: invalid nonce
