### ISSUE TITLE
FatalError for is_allowed()  after Woocommerce Update

### ISSUE THREAD

**Issue by christophberinger** [wpovernight/woocommerce-pdf-invoices-packing-slips#627]
Hi,

we love your plugin but today after a woocommerce update to = 8.2.0 2023-10-13 = we've got a fatal error on all plugin related views:

`Fatal error: Uncaught Error: Call to a member function is_allowed() on bool
in /home/customer/www/yogastudiofox.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/wcpdf-functions.php on line 48`

seems like the function expects an object but gets a boolean.

any ideas for this?

thanks and cheers

**Comment by alexmigf** [comment]
Hi @christophberinger 

Thank you for reporting this!

Do you have the trace of the error?

**Comment by christophberinger** [comment]
Hi @alexmigf,

this is all i got, was busy rolling back ;)
![Bildschirmfoto 2023-10-13 um 16 51 03](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/8081403/cad620d0-a5f0-4345-81ed-bb2c905efcd8)
![Bildschirmfoto 2023-10-13 um 16 51 16](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/8081403/91bab264-76e9-4318-94ab-d09924767e58)

**Comment by alexmigf** [comment]
@christophberinger this beta should fix the issue: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/releases/download/v3.7.0-beta-5/woocommerce-pdf-invoices-packing-slips.3.7.0-beta-5.zip

**Comment by christophberinger** [comment]
Will test it, thanks @alexmigf !
