### ISSUE TITLE
Order refund does not reflect on PDF Invoice.

### ISSUE THREAD

**Issue by sayful1** [wpovernight/woocommerce-pdf-invoices-packing-slips#63]
If I refund an order partially by quantity or by fee amount or refund shipping amount. There is no reflection on PDF invoice.

**Comment by Spreeuw** [comment]
This is for legal reasons: most countries require an invoice to be immutable. If you want to send your customer a fiscal document for the refund, you can create a credit note, basically a negative invoice accounting for the refunded items. With the free version of this plugin you will need to create this manually, outside of WooCommerce somewhere. The [Professional extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-professional/) of this plugin provides that as a built-in feature.
