### ISSUE TITLE
Discrepancies in Unit Price shown in PDF invoice when changed within OpenPOS Dashboard.

### ISSUE THREAD

**Issue by wasiqjaved** [wpovernight/woocommerce-pdf-invoices-packing-slips#642]
When using [OpenPOS](https://codecanyon.net/item/openpos-a-complete-pos-plugins-for-woocomerce/22613341)'s POS Dashboard, Unit Price can be changed before placing order. After placing order, PDF invoice is generated.

After placing order, changed 'Unit Price' is correctly displayed on Woocommerce's Order Details page, however PDF generated invoice still shows default Unit Price (not changed unit price displayed on specific Order ID).

**Comment by alexmigf** [comment]
We use the order object `get_line_subtotal` method divided by the item quantity, see here:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/019cf0830a510b3251c2d209d8180850002a59c1/includes/documents/abstract-wcpdf-order-document-methods.php#L1148-L1161

Do you know how they save the price change?

**Comment by wasiqjaved** [comment]
> We use the order object `get_line_subtotal` method divided by the item quantity, see here:
> 
> Do you know how they save the price change?
No. 

OpenPOS have an option in its settings which allow Cashier to change unit price of any item ([Photo](https://prnt.sc/qnwfx8)). 
It doesn't change its actual unit price from backend. It just changes unit price for that particular Order / transaction.

If you tell me to look for any particular hook or action, I can start from there.

**Comment by alexmigf** [comment]
I would say to start searching for data being saved when the order is placed, maybe `woocommerce_before_order_object_save` or other similar. If you need help with that send us an email to support@wpovernight.com mentioning this issue.

**Comment by wasiqjaved** [comment]
I've been digging this issue for some time. Here's what I have found.

In '**wp_postmeta**' table, order data by OpenPOS plugin is stored in a serialized PHP format. The **_op_item_data_details** meta key contains a comprehensive array of information about the order item, including the original and the updated prices, product details, tax information, and more.

In case of, lets say Order ID 3374 ([pastebin](https://appp.me/9sYsmC)) with following information:

- Product Name : Chicken (Charga) - With Skin
- Product ID : 2146
- Variation ID : 2406
- Variation Title : 2406
- Variation Selected : With Skin
- Product Unit Cost : $8.00
- Edited Unit Cost using POS : $18.00

the relevant parts of this serialized data appear to be:

- **price**: This seems to be the original price of the item (**8**).
- **custom_price**: This seems to be a field where a custom price might be stored (also **8** in this case).
- **final_price**: This is the updated price that was set using the POS (**18**).
- **final_price_incl_tax**: This is the updated price including tax, which also appears to be **18**.

The **has_custom_price_change** boolean (**b:1;**) indicates that a custom price change has been applied.

To reflect this updated price in your plugin, the invoice generation code should be modified to use **final_price** or **final_price_incl_tax** instead of **price** when fetching the unit price to display. The exact change needed would depend on how your plugin retrieves and uses this data.

I think what you need to do is modify that code to fetch the **final_price** or **final_price_incl_tax** from the order item meta instead of the standard price. You might need to unserialize the data first if it's stored serialized. Also esure that the modified code properly handles the inclusion or exclusion of tax, depending on how the PDF invoice plugin handles this.

From the **invoice.php** template code in your plugin, the unit price for each order item is displayed with the following line within the **foreach** loop:
`<td class="price"><?php echo $item['order_price']; ?></td>
`

Since OpenPOS is modifying the price and is correctly showing in the WooCommerce admin but not in the PDF invoice, the discrepancy could be because:

- Your plugin is fetching the original order item data before OpenPOS modifies it.
- OpenPOS modifies the data after your plugin fetches it.
- OpenPOS uses a custom field or meta key to store the modified price, which your plugin is not using.

To adjust your plugin to use the updated price, you would need to identify where OpenPOS stores this updated price (which seems to be in the serialized **_op_item_data_details** order meta) and then modify your plugin to use that value.

To achieve this, you may hook into your plugin's data preparation process using a filter like **wpo_wcpdf_order_item_data** which is often used to modify order item data before it's sent to the template. Here's somewhat an idea or example of how you may do that:

`add_filter('wpo_wcpdf_order_item_data', function ($item_data, $order, $order_type) {
    // Loop through each item and update the 'order_price'
    foreach ($order->get_items() as $item_id => $item) {
        // Fetch the updated price from OpenPOS meta
        $op_item_data = maybe_unserialize(wc_get_order_item_meta($item_id, '_op_item_data_details', true));

        if ($op_item_data && isset($op_item_data['final_price_incl_tax'])) {
            // Replace the order_price with the final_price_incl_tax from OpenPOS
            $item_data[$item_id]['order_price'] = wc_price($op_item_data['final_price_incl_tax']);
        }
    }

    return $item_data;
}, 10, 3);
`

It assumes that the updated price is stored in the **_op_item_data_details** meta key and that this key is serialized. You would need to replace **wc_get_order_item_meta** with the appropriate function call if OpenPOS uses a different method to store the price.

Sorry for the long reply.

**Comment by wasiqjaved** [comment]
**SOLUTION**

I found a way to resolve this issue.

There's a "Customizer" tab where you can edit "Invoice".

Inside, I saw that "**Regular Price**" was preselected in 'Item Columns'

To resolve this, I removed "**Regular Price**" and replaced it with **"Price"** with **"Single Price"** selected. This way, it showed exactly what was displayed on my Order page.

**Comment by alexmigf** [comment]
Ok, that's good to hear that. Didn't know that you had an extension. In that case I'm closing this issue for now.
