### ISSUE TITLE
"Disable for free products" sometimes doesn't work

### ISSUE THREAD

**Issue by BusinessBloomer** [wpovernight/woocommerce-pdf-invoices-packing-slips#66]
This function disables Invoice generation for free orders: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/ae50a2bb50a9db286289156af07f5e53249be73b/includes/class-wcpdf-main.php#L365-L368

However, at random, some orders at €0 or $0 (I have a currency switcher) do get an invoice, and I can't figure out why. Conditions are the same between orders with invoice and orders without it (order total = 0) so I have no idea.

Have you experienced this?

**Comment by Spreeuw** [comment]
This function disables the automatic generation for free orders, but the invoice can still be generated manually. I have recently introduced a new filter (`wpo_wcpdf_document_is_allowed`)that you could utilize if you want to disable the invoice entirely for free purchases:
`
add_filter('wpo_wcpdf_document_is_allowed','wpo_wcpdf_disable_free_invoices',10,2);
function wpo_wcpdf_disable_free_invoices( $is_allowed, $document ) {
	if ( $document->get_type() == 'invoice' && !empty($document->order) && $document->exists() == false ) {
		if ( $document->order->get_total() == 0 ) {
			$is_allowed = false;
		}
	}
	return $is_allowed;
}
`
Is it possible these odd orders were simply created manually in a batch export or by pressing the button by mistake?

**Comment by BusinessBloomer** [comment]
> Is it possible these odd orders were simply created manually in a batch export or by pressing the button by mistake?

Not possible, no :)

> This function disables the automatic generation for free orders, but the invoice can still be generated manually. I have recently introduced a new filter (wpo_wcpdf_document_is_allowed)that you could utilize if you want to disable the invoice entirely for free purchases:

Ok, this is great, so I can customize it e.g. disable invoices if order billing last name = empty. Thank you
