### ISSUE TITLE
Create settings sections

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#668]
As our plugin has evolved over the years, the number of settings has grown significantly. This expansion has led to a cluttered and overwhelming settings page, making it challenging for users to locate and manage specific configurations.

These issues will be addressed when we create a whole new UI for the plugin early next year. But for now it might be nice to already create distinct sections for the available settings.

**Comment by MohamadNateqi** [comment]
@Terminator-Barbapapa May I ask if you created a mockup for this, or would you prefer me to create one?

**Comment by Terminator-Barbapapa** [comment]
Perhaps we can use the new styling, where we will be using a serif font for headers. 

<img width="617" alt="Scherm­afbeelding 2023-12-27 om 21 26 09" src="https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/19350150/1c7060b8-0e1a-4f97-83bb-71f25e5b9a67">

```
#wpo-wcpdf-settings h3 {
    border-bottom: 1px solid #c3c4c7;
    padding-bottom: 0.35em;
    margin-bottom: 0;
    font-weight: normal;
    color: #222;
    font-family: serif;
    font-size: 1.7em;
    letter-spacing: -0.025em;
}
```

And with the following sections:

- Enable document

**General**

- Document title
- Attach to (various options)
- Create automatically for
- Disable for
- Number format
- Allow My Account invoice download

**Display options**

- Document number label
- Document date label
- Email address
- Phone number
- Customer notes
- COC number
- VAT number
- Shipping address
- Invoice date
- Invoice number

**Due date**

- Display due date
- Due date label
- Base date
- Allowed order statuses
- Allowed payment methods

**Advanced**

- PDF filename
- Next invoice number
- Reset invoice number yearly
- Keep PDF on server
- Mark as printed
- Unmark as printed
- Log invoice number generation
- Enable invoice number column
- Enable invoice date column
- Enable invoice number search
- Disable for free orders
- Always use most current settings

**Comment by MohamadNateqi** [comment]
@Terminator-Barbapapa I like the font style of header, it's modern and nice.

Sections are also great, but do you think the "Advanced" section could/better break into two sections, maybe?

**Comment by Terminator-Barbapapa** [comment]
@MohamadNateqi What are you proposing? 
@alexmigf Could you also take a look at this?

**Comment by MohamadNateqi** [comment]
@Terminator-Barbapapa I suggested that since I thought there might be many settings under the Advanced sections. But actually, it's hard to break it.

I think maybe the only settings we can separate from them are these three:

- Enable invoice number column
- Enable invoice date column
- Enable invoice number search

Maybe we better keep it the way it is right now.

**Comment by alexmigf** [comment]
I agree with Mohamad, this 3 options are a bit out of place I think, maybe in the display section would be better? But anyway, not a huge deal.

**Comment by Terminator-Barbapapa** [comment]
Perhaps we can create a section called 'Document display options' and 'Admin display options'? Where the latter is used to show the columns and enable the invoice number search?
