### ISSUE TITLE
txt

### ISSUE THREAD

**Issue by franc3sc0s92** [wpovernight/woocommerce-pdf-invoices-packing-slips#67]
Hi, i use this plug in with shop manager app. I want to return a txt for pos printer. Can you help me?

**Comment by Spreeuw** [comment]
This github channel is only meant to be used for issues, not for support questions. If you have any support questions, please post them to the support forum: https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips/ (I see you have also emailed us though, so we'll take it from there)
