### ISSUE TITLE
Warning: Trying to access array offset on value of type null (abstract-wcpdforder-documentmethods.php)

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#670]
A user reported this issue that is happening in the discount total row:

```
Warning: Trying to access array offset on value of type null in example.com/wpcontent/plugins/woocommerce-pdfinvoices-packingslips/includes/documents/abstract-wcpdforder-documentmethods.php on line 1030
```

Here is how the warning message is being displayed on the PDF document:

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/38109855/3a555169-b98c-4a09-a544-5ff526b5d421)

**Comment by alexmigf** [comment]
Not sure how that is possible if the array is declared in the inner function here: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/af4ac099eac28e2931d90d612768a770d5913f50/includes/documents/abstract-wcpdf-order-document-methods.php#L1020

**Comment by YordanSoares** [comment]
@alexmigf it was reported by a user ([here](https://secure.helpscout.net/conversation/2443007711/56531/)), but then they said they were using a custom PDF template, so it could be caused by their code instead. Feel free to close this issue, if there is nothing to fix on our side.

**Comment by alexmigf** [comment]
@YordanSoares you can close if the ticket is concluded as well and no need further investigations.

**Comment by alexmigf** [comment]
@YordanSoares what's the status of this?

**Comment by YordanSoares** [comment]
@alexmigf I just asked if the issue is still happening after switching to Simple to confirm whether it's fixed, or not. I'll close the issue, or update with more details, as soon they have replied.
