### ISSUE TITLE
Are you able to send packing slips diretly when order have been made.

### ISSUE THREAD

**Issue by emilpriverrc** [wpovernight/woocommerce-pdf-invoices-packing-slips#69]
Hi :D 

I am tying to be able to send packing slips directly to the company that have the website when an order have been made. Is that possible?

**Comment by Spreeuw** [comment]
Hello Emil,
This is one of the features of [our professional extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-professional/), which allows you to attach the packing slip to any of the default WooCommerce emails or to send it with a separate email ([Order Notification](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/configuring-the-order-notification-email/))that the Professional extension adds that is triggered by a specific status.

**Comment by emilpriverrc** [comment]
ok cool. Thanks :D
