### ISSUE TITLE
Improve the sorting of the invoice number column

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#696]
Currently, we order the invoice number column by `meta_value`, which work well with some formatted numbers, e.g. `INV-000123`:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/37c7d60fda123b03845ed704592978adc5b7f38a/includes/class-wcpdf-admin.php#L433

However, it doesn't work correctly with invoice number without a format, where the sorting behaves in an unexpected way, e.g. sorting the numbers like 1, 11, 111, 2, 22, 3, 33, 33, etc.

It can be fixed with this code snippet:

```php
/**
 * PDF Invoices & Packing Slips for WooCommerce:
 * Change the orderby value to 'meta_value_num' to sort invoice numbers without a format
 */
add_filter( 'wpo_wcpdf_invoice_number_column_orderby', function() { return 'meta_value_num'; } );
```

But I think we should try to improve this behavior by default, making the sorting smarter, so the code snippet above is no longer necessary.

**Comment by brualio** [comment]
Inspecting the code and the query, it seems like just replacing the original `meta_value` with `meta_value_num` -as in the snippet- should be enough. Here's an example of how it would sort some random data:

![imagen](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/153516591/18b8d67f-2237-4fda-a122-012b8e700fc8)
