### ISSUE TITLE
php compatibility checker errors

### ISSUE THREAD

**Issue by dwalkerpriv** [wpovernight/woocommerce-pdf-invoices-packing-slips#697]
the [PHP Compatibility Checker](https://wordpress.org/plugins/php-compatibility-checker/) plugin throws some errors when checking for our plugin's compatibility. this only occurs with the PDF plugins

![Screenshot 2024-01-24 170855](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/62675729/25b6ec1d-7070-45d6-9871-2d7185cef8f9)

The reports
---

PHP 7.2 incompatibilities:
---

FILE: vendor/dompdf/dompdf/src/Adapter/CPDF.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 177 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/phenx/php-font-lib/src/FontLib/EOT/File.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 77 | ERROR | The function mb_str_split() is not present in PHP version 7.3 or earlier 

FILE: vendor/phenx/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 36 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/sabberworm/php-css-parser/src/RuleSet/DeclarationBlock.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 803 | ERROR | Throwing exceptions from __toString() was not allowed prior to PHP 7.4 

FILE: vendor/symfony/polyfill-mbstring/bootstrap80.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 125 | ERROR | null coalesce equal operator (??=) is not present in PHP version 7.3 or earlier 

PHP 7.3 incompatibilities:
---

FILE: vendor/dompdf/dompdf/src/Adapter/CPDF.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 177 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/phenx/php-font-lib/src/FontLib/EOT/File.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 77 | ERROR | The function mb_str_split() is not present in PHP version 7.3 or earlier 

FILE: vendor/phenx/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 36 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/sabberworm/php-css-parser/src/RuleSet/DeclarationBlock.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 803 | ERROR | Throwing exceptions from __toString() was not allowed prior to PHP 7.4 

FILE: vendor/symfony/polyfill-mbstring/bootstrap80.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 125 | ERROR | null coalesce equal operator (??=) is not present in PHP version 7.3 or earlier 

PHP 7.4 incompatibilities:
---

FILE: vendor/dompdf/dompdf/src/Adapter/CPDF.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 177 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/phenx/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 36 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

PHP 8.0 incompatibilities:
---

FILE: vendor/dompdf/dompdf/src/Adapter/CPDF.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 177 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead 

FILE: vendor/phenx/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
 36 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead

**Comment by YordanSoares** [comment]
@dwalkerpriv it would be very useful to see the errors for the free plugin, but you need to use the latest release instead of a beta version to see the error reports, since this tool seems to get the plugin core files from WordPress.org ([see](https://wordpress.org/plugins/php-compatibility-checker/#5.%20why%20was%20my%20plugin%2Ftheme%20skipped%3F)), that should be also the reason why the extensions return a 404 error: Those plugins are not publicly available!

**Comment by dwalkerpriv** [comment]
@YordanSoares thanks for catch 👍

**Comment by YordanSoares** [comment]
@dwalkerpriv you're welcome! Do not forget to share the reports, that you will find after click on each PHP versions. Since we are officially compatible with PHP 7.2 and higher ([see](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/main/readme.txt#L7)), we would only need 7.2, 7.3, 7.4 and 8.0.
