### ISSUE TITLE
Undefined variable: sanitize_function

### ISSUE THREAD

**Issue by psaikali** [wpovernight/woocommerce-pdf-invoices-packing-slips#70]
I'm getting PHP notices because of wrongly assigned `$sanitize_function` variable ([== instead of = in the code](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/a5f5e8fce4b476f31a14e5a251aec016d6f5914e/includes/class-wcpdf-setup-wizard.php#L233))

```
PHP Notice:  Undefined variable: sanitize_function in .../wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-setup-wizard.php on line 235
```

**Comment by Spreeuw** [comment]
Thanks for reporting!
