### ISSUE TITLE
Bug: "I am the wizard" button is not working!

### ISSUE THREAD

**Issue by MohamadNateqi** [wpovernight/woocommerce-pdf-invoices-packing-slips#714]
The banner displayed when the plugin is installed for the first time includes a button labeled "I am the wizard." However, this button does not dismiss the banner.

![image](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/136313810/273545d5-7858-4c19-847e-143542a75237)

**Comment by brualio** [comment]
I can't replicate this issue in a new WordPress install.

Plugin version: 3.8.0-beta-1
Latest WooCoommerce and WordPress.

When I click the "I am the wizard" button, the dialog goes away as intended.

**Comment by MohamadNateqi** [comment]
@brualio Please remove the option key (`wpo_wcpdf_install_notice_dismissed`), then go to the Orders page and try again.

**Comment by brualio** [comment]
Understood! It seems that the button is working if you click it from the General "PDF Invoices" page, but where you said, the Orders page, it isn't.
