### ISSUE TITLE
Using getters to access Woo class properties

### ISSUE THREAD

**Issue by MohamadNateqi** [wpovernight/woocommerce-pdf-invoices-packing-slips#716]
The `get_tax_rate()` in the `Order_Document_Methods` class directly accesses class properties of the `WC_Order_Item` child classes of Woocommerce, which it needs to use the getter provided. This way of accessing properties for `WC_Order_Item_Coupon` can raise this log:
`The WC_Order_Item_Coupon::offsetGet function is deprecated since version 4.4.0.`

This first happened in this [PR](https://github.com/wpovernight/woocommerce-pdf-ips-templates/pull/281#issuecomment-1943549593).

**Comment by alexmigf** [comment]
This only affects coupons: https://github.com/woocommerce/woocommerce/blob/e00f49a0b17f0b1336965e6cc39226e3db6d61d5/plugins/woocommerce/includes/class-wc-order-item-coupon.php#L144-L152

I think we should keep the others like it is.

**Comment by MohamadNateqi** [comment]
There are getter methods in other child classes that we can use too.
Do you think it would be better to update it for all of them?

**Comment by alexmigf** [comment]
We could, but we need to check when those methods were made available because this plugin minimum version is WC 3.0.

**Comment by alexmigf** [comment]
I wanted to avoid that, that's why I was suggesting to change the code for coupons only.

**Comment by MohamadNateqi** [comment]
Are there any issues with bumping up the WC version?

**Comment by alexmigf** [comment]
While updating the WooCommerce version may seem straightforward, it's essential to consider the broader implications. Forcing users to update could pose challenges for those running older versions of WooCommerce and other plugins. This could lead to resistance from some store owners who prefer to avoid extensive updates. Unless this version bump addresses critical issues, it might be prudent to refrain from making the change solely for a minor feature enhancement.

**Comment by alexmigf** [comment]
@MohamadNateqi did you investigate the versions when the methods were introduced?
