### ISSUE TITLE
Problem with polish diacritics in generated PDF invoice

### ISSUE THREAD

**Issue by konopka90** [wpovernight/woocommerce-pdf-invoices-packing-slips#74]
Hi, I see a problem with polish diacritic in generated PDF invoice, the letter "ł" is not encoded properly. 

![image](https://user-images.githubusercontent.com/5208485/79390305-bf8ce200-7f6f-11ea-8762-278c9b779954.png)

Is it some configuration issue or some bug?

What's more the word "Wysyłka" is correct. Looks like problem with currency only.

**Comment by Spreeuw** [comment]
It looks like you may have set the "Extended currency symbol support" which is primarily for more 'exotic' currencies. Can you try turning that off to see if it resolves the issue?

**Comment by konopka90** [comment]
It fixed issue. I dont know why it was checked, maybe by accident. Thx, have a nice day!
