### ISSUE TITLE
WordPress 6.5-beta3: Issue with the numbering system

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#742]
A user has reported that WordPress 6.5-beta3 is producing issues: The PDF can be accessed but the number increments +1 anytime the link gets opened.

See: https://wordpress.org/support/topic/issue-with-wordpress-6-5-prerelease-beta-3/

**Comment by alexmigf** [comment]
It is worth mentioning that he also ran the test in PHP 8.3.

**Comment by MohamadNateqi** [comment]
It was reported that pdf preview increments the invoice number.
I could not replicate that issue, but I have also faced some other issues with different PHP versions on `6.5-beta-3` (HPOS on and off).
The RC 3 was released on March 19, and everything works fine with this version; I didn't experience any issues mentioned above.

**Comment by alexmigf** [comment]
Maybe we should contact the customer to test again with the 6.5 stable version?

**Comment by MohamadNateqi** [comment]
I agree.

I'll message them if it's also OK with you.

**Comment by MohamadNateqi** [comment]
Based on tests conducted and the [customer report](https://wordpress.org/support/topic/issue-with-wordpress-6-5-prerelease-beta-3/#post-17551320), no compatibility issue found, and I think this issue could be closed.
@alexmigf
