### ISSUE TITLE
HPOS: add Invoice number to search type selector

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#748]
Following [this PR](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/747) review, I notice that HPOS has a new selector in the order list search, maybe we could add the Invoice number option there:

![Screenshot from 2024-03-13 16-15-31](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/9986bd5d-d08d-4d0f-8e15-98e3117a387a)

**Comment by alexmigf** [comment]
@BrunoPavlinic98 these are my advanced settings:

![Screenshot from 2024-05-24 15-53-35](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/assets/533273/5375a645-05c0-452a-bda8-7bce4c2ed0cd)

I think this PR would be helpful: https://github.com/woocommerce/woocommerce/pull/45954

This is where the dropdown is located: https://github.com/woocommerce/woocommerce/blob/4ddfd43864eccde911ab6d1947773e2efb80773b/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L1632-L1662

**Comment by BrunoPavlinic98** [comment]
@alexmigf and @MohamadNateqi thanks for the help. I had this issue due to lower woocommerce version.
