### ISSUE TITLE
language support?

### ISSUE THREAD

**Issue by wesleyxiao** [wpovernight/woocommerce-pdf-invoices-packing-slips#75]
hello, my invoice can generate successfully but chinese character was not able to see, show as Garbled，any setting i missing?

**Comment by Spreeuw** [comment]
Chinese characters are not included in the default font, you can either include a custom font ([documentation here](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/using-custom-fonts/)) or use the [mpdf extension](https://github.com/wpovernight/woocommerce-pdf-ips-mpdf/releases) (CJK version)
