### ISSUE TITLE
Check if the document type exists to avoid a fatal error

### ISSUE THREAD

**Issue by YordanSoares** [wpovernight/woocommerce-pdf-invoices-packing-slips#766]
[This user](https://wordpress.org/support/topic/fatal-error-call-to-a-member-function-is_allowed-on-bool-3) has reported that the document query returns a fatal error when the document type does not exist. I tried to reproduce the scenario and confirmed that the error happens. Here is the stack trace I received:

```
Fatal error: Call to a member function is_allowed() on bool

/home/example.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/wcpdf-functions.php (82)

#0 /home/example.com/public_html/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-main.php(545): wcpdf_get_document()
#1 /home/example.com/public_html/wp-includes/class-wp-hook.php(324): WPO\WC\PDF_Invoices\Main->generate_document_ajax()
#2 /home/example.com/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /home/example.com/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/example.com/public_html/wp-admin/admin-ajax.php(192): do_action()
#5 {main}
```

**Comment by alexmigf** [comment]
@YordanSoares not sure if it's related, but the document type is not correct on their URL:

> /admin-ajax.php?action=generate_wpo_wcpdf&document_type=**invoic1e**&order_ids=123&access_key=3ee5e7e8fa
