### ISSUE TITLE
Apply footer CSS to the wrapper

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#772]
As we've now introduced a new wrapper to our footer to be compatible with mPDF, we should apply the footer styling to the `htmlpagefooter` instead of onto `#footer`.

We should then also update the 'Repeating headers and footers' documentation article.

**Comment by BrunoPavlinic98** [comment]
I am closing this task because no code changes are needed. We will update the [documentation](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/repeating-headers-footers/) and users will be able to choose between domPDF and mPDF.
