### ISSUE TITLE
Download PDF Invoices via Woocommerce REST api

### ISSUE THREAD

**Issue by gadget-man** [wpovernight/woocommerce-pdf-invoices-packing-slips#800]
I'm providing registered customers with a report on orders they've placed in an external dashboard, using the Woocommerce REST API. For each order, I'd like to be able to give the customer the option to download a further copy of their PDF invoice.

It would be great if there was a mechanism to be able to do this. I can already see all the order details including several `_wcpdf` but can't see anything specific to allow me to externally access the invoice PDF itself.

**Comment by alexmigf** [comment]
We are going to provide some REST API endpoints in our Professional extension soon, we don't have plans to do this on the free plugin for now.

Hope that helps!

https://github.com/wpovernight/woocommerce-pdf-ips-pro/pull/378

**Comment by usselite** [comment]
Hi @alexmigf is it available?

**Comment by alexmigf** [comment]
It's expected to be released with our Professional extension version 2.16.0.

**Comment by alexmigf** [comment]
Hi @usselite 

We are completing the final reviews before releasing a new version of Pro, which will include this feature.

**Comment by alexmigf** [comment]
@usselite, this feature is available exclusively in our [Professional extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-bundle/). You’ll find a new tab with setup instructions under the "Advanced" section of the plugin settings menu.

**Comment by usselite** [comment]
Hi @alexmigf, yes I did see that (we have pro extension), I might misunderstand how this is supposed to work, but there's no real end-point where you can download? 

These are the options available:
1. Retrieve an order
2. Create or regenerate a document
3. Delete a document

**Comment by alexmigf** [comment]
You can enable the "Keep PDF on Server" document setting, then access the PDF archive URL through the order metadata using the REST API order endpoint.
