### ISSUE TITLE
add option to always show shipping address on invoice

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#85]
Change this:
![display-shipping-address-old](https://user-images.githubusercontent.com/3217773/82536108-3eb19f00-9b48-11ea-8055-1d16f05f6693.png)

to this:
![display-shipping-address-new](https://user-images.githubusercontent.com/3217773/82536112-42452600-9b48-11ea-96ee-f5ae0848fe4a.png)

(and do the same for packing slip, proforma etc.)

Existing templates do not support this yet:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e9ae661705bacd3ca650d769cf6bb9b6a66a2a7d/templates/Simple/invoice.php#L43

so I see two possibilities:

1. We use the [wpo_wcpdf_ships_to_different_address](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/e9ae661705bacd3ca650d769cf6bb9b6a66a2a7d/includes/documents/abstract-wcpdf-order-document-methods.php#L95) filter to return true for all documents with the 'Always' setting enabled.
2. We change the template and accept that legacy templates will not support the option.

Any thoughts?

**Comment by alexmigf** [comment]
Option 1 could be more safe.

**Comment by Terminator-Barbapapa** [comment]
I would also go for option 1

**Comment by Spreeuw** [comment]
what's the risk of option 2? It would look like this:
``` php
 <?php if ( isset($this->settings['display_shipping_address']) && ( $this->ships_to_different_address() || $this->settings['display_shipping_address'] == 'always' ) ) { ?> 
```
So legacy templates would still work, they would just not work with the 'always' option. Personally I think this is a cleaner solution and for those templates that do not support it we can help people to update it.

**Comment by Spreeuw** [comment]
I have decided for option 2 after all, it's better moving forward and a cleaner solution, I have added @alexmigf for review
