### ISSUE TITLE
Simplify the due date option

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#853]
I think the due date option can be simplified in the free version, by not providing preset options. I think this setting should always be an input field, that defaults to 30 days when enabled. 

So it could look something like this:

<img width="281" alt="Scherm­afbeelding 2024-08-30 om 17 00 52" src="https://github.com/user-attachments/assets/6e4b5f77-ae0a-4885-99f3-3d0a7e46752b">

The input can be disabled when the checkbox is unchecked. Like this:

<img width="299" alt="Scherm­afbeelding 2024-08-30 om 17 03 54" src="https://github.com/user-attachments/assets/e17b9aed-a81e-471a-b70f-5405b64fc791">

I think we can remove the placeholder option we provide in the Professional extension. Users can simply uncheck the checkbox and use the placeholder in the Customizer if they need to place the due date in a custom position.

**Comment by Terminator-Barbapapa** [comment]
@alexmigf @MohamadNateqi Let me know your thoughts.

**Comment by alexmigf** [comment]
I agree, seems more simple to me.

**Comment by MohamadNateqi** [comment]
Nice and simple. :ok_hand:
I'll apply it.
