### ISSUE TITLE
Clean up locks

### ISSUE THREAD

**Issue by DavidAnderson684** [wpovernight/woocommerce-pdf-invoices-packing-slips#854]
@alexmigf The current code is using per-order lock names like `updraft_lock_wpo_wcpdf_main_semaphore_lock_order_2177401_email_customer_completed_order`.

On the site I'm looking at currently, there are up to 5 separate locks per order (one lock per order status). The locks aren't being cleaned up, and consequently, these locks account for over 40% of rows in the `options` table (or over 90% once I eliminate a large number of rows form a long-running WooCommerce bug which also creates zillions of rarely-used rows).

Solution:

1) To clean-up already-existing ones: delete unused locks (where the `value` is `0`)

2) To stop new ones accumulating: for rarely-used locks (e.g. ones with per-order names), call the `delete()` method in the `Updraft_Semaphore_3_0` class after releasing the lock.

Step 1) could also be run as a scheduled task periodically to catch any that aren't properly released/deleted.

**Comment by alexmigf** [comment]
@DavidAnderson684 I have implement some changes [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/842) (not released yet). Do you see more improvements?

**Comment by DavidAnderson684** [comment]
@alexmigf The SQL statements in the methods `cleanup_expired_locks()` and `count_expired_locks()` doesn't look at the option value; there's nothing in those statements that enforces the "expired" part. It should check that the value is `0`; and it'd be more precise to call it "unlocked" or "unused" rather than "expired". Maybe put a `WPOvernight_` in the class name too to make it clear that the class has diverged meaningfully/significantly from the class it was forked from?
