### ISSUE TITLE
PHP Fatal error: Call to undefined function ini_set

### ISSUE THREAD

**Issue by maltfield** [wpovernight/woocommerce-pdf-invoices-packing-slips#859]
This bug report fixes a PHP Fatal error caused by PEAR.php when ini_set is disabled

# Problem

There is a bug in `vendor/dompdf/dompdf/src/Dompdf.php at the following lines:

```
        @ini_set('pcre.jit', '0');
```

and

```
            @ini_set('pcre.jit', $this->pcreJit);
```

These lines causes a PHP Fatal error on hardened systems with the `ini_set` function disabled.

```
PHP Fatal error:  Uncaught Error: Call to undefined function ini_set() in /usr/share/php/PEAR.php:52\n...
```

# Why this matters

For security reasons, orgs frequently configure php.ini to be hardened by adding many dangerous functions to the `disable_functions` variable in the php.ini file. For example, it's common to disable the 'exec' function

```
disable_functions = exec
```

Of course, if a php script could modify the php configuration, then it would defeat any hardening done by setting `disable_functions`. As such, it's common to add `ini_set` to the `disable_functions`

```
disable_functions = exec, ini_set
```

# Solution

To fix the PHP Fatal error, we should always check to see if the `ini_set` function exists before attempting to call it

```
if( function_exists( 'ini_set') ){
        @ini_set('pcre.jit', '0');
}
```

# Context

This error was discovered on a server running the latest version of all software on the latest version of Debian, at the time of writing.

```
root@host:~# cat /etc/issue
Debian GNU/Linux 12 \n \l

root@host:~# 

root@host:~# dpkg -l | grep -iE 'php-common|php-pear'
ii  php-common                      2:93                                    all          Common files for PHP packages
root@host:~# 
```

**Comment by maltfield** [comment]
See also upstream bug report

 * https://github.com/dompdf/dompdf/issues/3523

**Comment by maltfield** [comment]
This appears to be a regression bug?

 * https://github.com/dompdf/dompdf/pull/2049

**Comment by alexmigf** [comment]
It appears that this issue is unrelated to our plugin, so I will be closing the ticket for now.

**Comment by maltfield** [comment]
well, it is a bug in this plugin. But it is valid that it's *caused* by an upstream library that you're using.
