### ISSUE TITLE
unify settings retrieval/saving/deleting

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/woocommerce-pdf-invoices-packing-slips#88]
With the newly added regenerate functionality, more control over settings operations was required that was not possible with the default `get_settings` method, so it is currently implemented with its own functions:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1231686395637d5d66e47ea66ea7fedfcd5d69b9/includes/documents/abstract-wcpdf-order-document.php#L306-L311
This leads to code duplication, so I propose to unify this in a more reusable way. A simple `save_settings()` method may be enough, reducing the above (and similar calls in the `init()` method)  to:
```php
$this->settings = $this->get_settings( true );
$this->save_settings();
```
or perhaps even a separate function for the above lines, so that you can use something like `$this->init_settings()`.

**Comment by alexmigf** [comment]
There's an [`init_settings()`](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/72d2a02369358f966d252f5583fdeb1f51ea9926/includes/documents/abstract-wcpdf-order-document.php#L123) method already which is extended by the documents.

**Comment by Spreeuw** [comment]
That seems unrelated to this issue to me?

**Comment by alexmigf** [comment]
> or perhaps even a separate function for the above lines, so that you can use something like $this->init_settings().

You weren't recommending to create a new method with this same name here?

**Comment by Spreeuw** [comment]
No, consider that just pseudo-code: we can't change existing methods that are already in use by document extensions.

Note that a few things have changed since opening this issue 2 years ago, so it should be approached based on the intention (reducing code duplication around settings retrieval/saving/deletion), not necessarily on the specific suggestions.
