### ISSUE TITLE
Table order item row breaks to second page

### ISSUE THREAD

**Issue by dwalkerpriv** [wpovernight/woocommerce-pdf-invoices-packing-slips#898]
Users have reported an issue in the with the second row of order items appearing beginning on another page, even when there is enough space to print everything

![Screenshot 2024-10-28 143808](https://github.com/user-attachments/assets/f4f1d0d8-189a-4926-b73b-e99c106720d0)

**Comment by alexmigf** [comment]
@dwalkerpriv i'm not able to reproduce this issue locally. What is the footer height of the screenshot above?

**Comment by dwalkerpriv** [comment]
@alexmigf  It's the default 2cm. On further testing, it happens when there are 3 or more items, or when the customer note section has information in it

**Comment by dwalkerpriv** [comment]
@alexmigf another user who has downgraded to v3.8.7 from v3.9.0 is having the issue. They didn't have it when they first downgraded, though. The issue then reoccurred

**Comment by alexmigf** [comment]
@dwalkerpriv I’m still unable to replicate this issue. Could you set up a staging environment and share the details with me on Slack?

**Comment by dwalkerpriv** [comment]
@alexmigf I've set up a staging site with these details

URL: https://purchasedisease.s2-tastewp.com
username Username: admin
password Password: kebyGHLvyeE

The issue is not there. I'll ask the user to run an update to see if it persists

**Comment by dwalkerpriv** [comment]
The user has confirmed that the update has solved the issue.
