### ISSUE TITLE
Fatal Error: Website unreachable due to this plugin after upgrading WooCommerce and Wordpress

### ISSUE THREAD

**Issue by ozgurkazancci** [wpovernight/woocommerce-pdf-invoices-packing-slips#908]
Hello there,

I've "PDF Invoices & Packing Slips for WooCommerce" installed, version 3.9.0, and it was working correctly until today.

Today, I updated Woocommerce to latest version: 9.4.1 and Wordpress to latest version: 6.7

However, immediately afterwards, my website was completely unreachable, giving "Fatal Error".

Web server's error.log file reports;

2024/11/13 16:14:52 [error] 22705#100255: *107170 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "\WPO\WC\PDF_Invoices\Updraft_Semaphore_3_0" not found in /usr/local/www/eshop/wp-includes/class-wp-hook.php:324

I then moved the plugin's folder out of the "plugins" directory, and my site was back.

FYI,

Regards.
Özgür Konstantin.

**Comment by alexmigf** [comment]
Hi @ozgurkazancci 

We apologize for the inconvenience.

It seems that [this PR](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/900) may have resolved the issue. Could you try our [latest beta version](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/releases/download/v3.9.1-beta-1/woocommerce-pdf-invoices-packing-slips.3.9.1-beta-1.zip) to confirm?

**Comment by ozgurkazancci** [comment]
Hi @alexmigf 

Thank you for your pretty fast response.

The latest beta version solved the issue,

Many thanks.
