### ISSUE TITLE
Add new setting for 'Invoice notes'

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#95]
Add a 'Invoice notes' section to the PDF invoice data tab before... Just like the 'customer notes' but specifically for the invoice, which can be entered in the backend.

**Comment by alexmigf** [comment]
@Spreeuw 

About this, i think we talked before but i can't find the conversation. The notes are added in the document settings correct?

**Comment by Spreeuw** [comment]
no, these are per-order notes, which would be in the "PDF Invoice Data" panel.
